'use strict';
const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),WebSocket=require('ws');
const base='http://127.0.0.1:18871',sockets=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
const server=spawn(process.execPath,['server.cjs'],{cwd:require('node:path').join(__dirname,'..'),env:{...process.env,PORT:'18871'},stdio:['ignore','pipe','inherit']});
async function client(){const ws=new WebSocket(base.replace('http','ws')+'/room');sockets.push(ws);ws.messages=[];ws.on('message',raw=>ws.messages.push(JSON.parse(raw)));await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject)});ws.sendObject=m=>ws.send(JSON.stringify(m));ws.wait=async test=>{for(let n=0;n<150;n++){const i=ws.messages.findIndex(test);if(i>=0)return ws.messages.splice(i,1)[0];await sleep(20);}throw Error('Timed out waiting for room response');};return ws;}
(async()=>{await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',()=>reject(Error('Server exited early')))});
try{assert.equal((await fetch(base+'/health')).status,200);for(const file of ['/.git/config','/package.json','/server.cjs','/node_modules/ws/index.js'])assert.equal((await fetch(base+file)).status,404);
for(const kind of ['star','tide']){const a=await client();a.sendObject({type:'join',game:kind,create:true});const first=await a.wait(m=>m.type==='joined');assert.equal(first.role,0);assert.deepEqual((await a.wait(m=>m.type==='state')).online,[true,false]);const b=await client();b.sendObject({type:'join',game:kind,code:first.code});const second=await b.wait(m=>m.type==='joined');assert.equal(second.role,1);await a.wait(m=>m.type==='state'&&m.online.every(Boolean));
const extra=await client();extra.sendObject({type:'join',game:kind,code:first.code});assert.match((await extra.wait(m=>m.type==='error')).message,/两位/);extra.close();
a.messages=[];a.sendObject({type:'input',keys:kind==='star'?['ArrowRight']:['KeyD']});const state1=await a.wait(m=>m.type==='state');await sleep(250);const state2=await a.wait(m=>m.type==='state'&&m.state.t>state1.state.t+.1);assert.notEqual(state2.state.players[0].x,state1.state.players[0].x);a.sendObject({type:'input',keys:[]});
a.sendObject({type:'pause',value:true});const paused=await a.wait(m=>m.type==='state'&&m.paused);await sleep(100);a.messages=[];const still=await a.wait(m=>m.type==='state');assert.equal(still.state.t,paused.state.t);const x=still.state.players[1].x;a.sendObject({type:'pause',value:false});a.sendObject({type:'input',keys:kind==='star'?['KeyD']:['ArrowRight']});await sleep(200);a.messages=[];assert.equal((await a.wait(m=>m.type==='state'&&!m.paused)).state.players[1].x,x);
a.sendObject({type:'level',level:99});await sleep(80);a.messages=[];assert.equal((await a.wait(m=>m.type==='state')).state.level,0);b.close();await a.wait(m=>m.type==='state'&&!m.online[1]);const replacement=await client();replacement.sendObject({type:'join',game:kind,code:first.code,token:second.token});assert.equal((await replacement.wait(m=>m.type==='joined')).role,1);await a.wait(m=>m.type==='state'&&m.online.every(Boolean));a.close();replacement.close();console.log(kind+': creation, capacity, movement, pause, isolation, invalid level, reconnect passed');}
const wrong=await client();wrong.sendObject({type:'join',game:'star',code:'000000'});assert.match((await wrong.wait(m=>m.type==='error')).message,/没有找到/);wrong.close();console.log('Network tests passed');
}finally{sockets.forEach(s=>s.terminate());server.kill();}})().catch(e=>{console.error(e);server.kill();process.exitCode=1;});
