(function(root){'use strict';
const rect=(id,x,z,w,d,y=0)=>({id,x,z,w,d,y});
const obj=(id,type,x,z,role=-1,y=0)=>({id,type,x,z,role,y});
const wall=(id,x,z,w,d,h=4)=>({...rect(id,x,z,w,d),h});
const keys=[{up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',jump:'KeyX',switch:'ShiftLeft',use:'ControlLeft',camL:'KeyQ',camR:'KeyE'}, {up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',jump:'Space',switch:'Backspace',use:'Enter',camL:'Comma',camR:'Period'}];
const stages=[
 {name:'01 · 盐牢醒来',theme:'prison',subtitle:'从彼此的牢门开始',bounds:[13,29],spawn:[[-5,22],[5,22]],exit:[0,-25],floors:[rect('base',0,0,26,58)],walls:[wall('divider',0,19,.7,13),wall('cellL',-10,19,.6,13),wall('cellR',10,19,.6,13),wall('desk',0,0,5,2,1.2)],objects:[obj('release0','lever',-7,18,0),obj('release1','lever',7,18,1),obj('key','key',0,-3,1),obj('seal0','plate',-5,-18,0),obj('seal1','plate',5,-18,1),obj('relic','relic',-10,-10)],guards:[[-1,-5,1,0]],goal:'分别拉下牢房拉杆，为对方开门；再夺回巡逻队的钥匙。'},
 {name:'02 · 守卫长厅',theme:'hall',subtitle:'一个制造声响，一个拆除警报',bounds:[19,36],spawn:[[-4,30],[4,30]],exit:[0,-32],floors:[rect('base',0,0,38,72)],walls:[wall('pillarA',-5,13,4,5),wall('pillarB',5,1,4,5),wall('pillarC',-5,-13,4,5),wall('screenA',-13,1,8,.8),wall('screenB',13,-13,8,.8)],objects:[obj('alarm0','alarm',-13,13,1),obj('alarm1','alarm',13,1,1),obj('alarm2','alarm',-13,-16,1),obj('seal0','plate',-5,-27,0),obj('seal1','plate',5,-27,1),obj('relic','relic',14,24)],guards:[[-11,12,0,0],[11,2,0,0],[-11,-15,0,0]],goal:'拆除三处警报。烁投出诱饵或用盾牌牵制，岚从侧面接近装置。'},
 {name:'03 · 齿轮断塔',theme:'tower',subtitle:'桥需要有人留在另一端',bounds:[13,34],spawn:[[-3,28],[3,28]],exit:[0,-29],floors:[rect('south',0,19,26,30),rect('middle',0,-10,26,14),rect('north',0,-28,26,12),rect('step1',6,-26,3,3,.6),rect('step2',9,-26,3,3,1.2),rect('step3',9,-29,3,3,1.8)],walls:[],objects:[obj('bridgePlate0','plate',-4,7,0),obj('winch0','winch',4,-7,1),obj('bridgePlate1','plate',4,-14,1),obj('winch1','winch',9,-29,0,1.8),obj('relic','relic',-10,-10)],guards:[],goal:'烁站住橙色压板，岚过第一座桥锁紧绞盘；第二座桥交换留守，烁攀上齿轮台。'},
 {name:'04 · 黑潮追城',theme:'chase',subtitle:'逃跑时，也要为同伴清路',bounds:[13,49],spawn:[[-3,42],[3,42]],exit:[0,-44],floors:[rect('base',0,0,26,98)],walls:[wall('hurdle0',-5,22,10,.7,.65),wall('hurdle1',5,2,10,.7,.65),wall('hurdle2',-5,-19,10,.7,.65)],objects:[obj('debris0','debris',-5,29,0),obj('chain0','chain',5,28,1,1),obj('debris1','debris',5,9,0),obj('chain1','chain',-5,8,1,1),obj('debris2','debris',-5,-12,0),obj('chain2','chain',5,-13,1,1),obj('relic','relic',10,-27)],guards:[],goal:'黑潮正在逼近！烁砸开路障，岚射断吊链。遇低栏要跳，两人一起逃向海光。'},
 {name:'05 · 失落海岸',theme:'coast',subtitle:'走进不同的岔路，找回出海装备',bounds:[29,35],spawn:[[-4,28],[4,28]],exit:[0,-31],floors:[rect('land',0,7,58,56),rect('island',0,-31,18,8)],walls:[wall('rock0',-11,4,5,9,3),wall('rock1',11,4,5,9,3),wall('wreck',17,-9,7,4,2)],objects:[obj('tideWheel','wheel',-19,10,1),obj('rope','rope',-22,-10,0),obj('counterweight','plate',19,12,0),obj('chart','chart',23,-12,1),obj('raft','raft',0,-16,-1),obj('relic','relic',-25,22)],guards:[[-20,-3,1,1],[22,-2,1,1]],goal:'分头寻找绳索与海图。岚转潮门让烁进洞；烁压住残骸配重，让岚攀取海图。'},
 {name:'06 · 双月遗迹',theme:'ruins',subtitle:'有人照亮符文，才有人能射中它',bounds:[21,35],spawn:[[-7,29],[7,29]],exit:[0,-31],floors:[rect('base',0,0,42,70)],walls:[wall('spine',0,5,2,44,4),wall('mazeL0',-13,11,15,1),wall('mazeR0',13,0,15,1),wall('mazeL1',-13,-9,15,1)],objects:[obj('torch0','torch',-15,20,0),obj('rune0','rune',15,17,1,1.4),obj('torch1','torch',-15,2,0),obj('rune1','rune',15,-5,1,1.4),obj('torch2','torch',-15,-20,0),obj('rune2','rune',15,-22,1,1.4),obj('relic','relic',-18,-28)],guards:[[-9,0,1,2],[9,-15,1,2]],goal:'烁依次点亮左路月火；岚在右路射中对应符文。每次点亮维持12秒，错过可再点。'},
 {name:'07 · 风暴军械库',theme:'armory',subtitle:'新的装备，必须一起赢来',bounds:[18,25],spawn:[[-4,20],[4,20]],exit:[0,-21],floors:[rect('base',0,0,36,50)],walls:[wall('cover0',-9,0,3,5,2),wall('cover1',9,0,3,5,2)],objects:[obj('trial0','plate',-4,10,0),obj('trial1','plate',4,10,1),obj('shield','shield',-5,-15,0),obj('stormbow','stormbow',5,-15,1),obj('relic','relic',14,-15)],guards:[],goal:'同时站上试炼印记。烁用盾击剥开重甲，岚用弓箭击败敌人；守住三波，再领取风暴装备。'},
 {name:'08 · 潮王苏醒',theme:'boss',subtitle:'挡住风暴，击中它的心脏',bounds:[24,29],spawn:[[-5,23],[5,23]],exit:[0,-25],floors:[rect('arena',0,0,48,58)],walls:[wall('ruin0',-16,2,3,5,2),wall('ruin1',16,2,3,5,2)],objects:[obj('relic','relic',20,18)],guards:[],goal:'烁靠近潮王，抬盾迎住蓄力震波，让核心暴露；岚从侧后方射击核心。注意跳过扩散震环和落石。'}
];
const inside=(x,z,r,m=0)=>Math.abs(x-r.x)<r.w/2+m&&Math.abs(z-r.z)<r.d/2+m;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
class Adventure{
 constructor(level=0){this.onEvent=()=>{};this.bindings=keys.map(k=>({...k}));this.relics={};this.load(level);}
 emit(type,text,extra={}){this.onEvent({type,text,...extra});}
 load(level,flags={}){this.level=level;this.config=stages[level];this.flags={...flags};this.t=0;this.shots=[];this.decoys=[];this.effects=[];this.finish=0;this.finished=false;this.fog=49;this.recoveries=0;this.players=this.config.spawn.map(([x,z],id)=>({id,x,z,y:0,yaw:0,face:0,hp:5,vy:0,ground:true,mode:0,cool:0,shield:0,inv:0,down:0,moving:0,checkpoint:{x,z,y:0},action:0}));this.enemies=this.config.guards.map((a,i)=>this.enemy('g'+i,...a));this.boss={x:0,z:-10,y:0,hp:18,max:18,phase:1,state:'idle',timer:4,weak:0,ring:-1,cycle:0};if(level===7&&this.flags.bossDead)this.boss.hp=0;if(level===6&&this.flags.trial&&!this.flags.trialDone)this.spawnWave();this.emit('load');}
 enemy(id,x,z,patrol=1,kind=0,armor=false){return{id,x,z,homeX:x,homeZ:z,hp:kind===1?2:3,max:kind===1?2:3,armor,stun:0,alert:false,target:0,attack:0,dead:0,patrol,kind,face:0};}
 save(){return{level:this.level,flags:this.flags,relics:this.relics};}
 floors(){const f=this.flags,ls=this.config.floors.slice();if(this.level===2){if(f.hold0||f.winch0)ls.push(rect('bridge0',0,.5,4,7));if(f.hold1||f.winch1)ls.push(rect('bridge1',0,-19.5,4,5));}if(this.level===4&&f.raft)ls.push(rect('raftBridge',0,-24,4,10));return ls;}
 gates(){const f=this.flags;let r=[];if(this.level===0){if(!f.release1)r.push(wall('cell0',-5,12,10,.7));if(!f.release0)r.push(wall('cell1',5,12,10,.7));if(!f.key||!f.seals)r.push(wall('exitGate',0,-21,26,.8));}if(this.level===1&&!f.seals)r.push(wall('exitGate',0,-29,38,.8));if(this.level===3)for(let i=0;i<3;i++)if(!f['debris'+i]||!f['chain'+i])r.push(wall('gate'+i,0,25-i*21,26,.7));if(this.level===4){if(!f.rope&&!(f.tideUntil>this.t))r.push(wall('tideGate',-22,-5,10,.7));}if(this.level===5&&![0,1,2].every(i=>f['rune'+i]))r.push(wall('exitGate',0,-28,42,.8));if(this.level===6&&!f.shield)r.push(wall('exitGate',0,-19,36,.8));if(this.level===7&&!f.bossDead)r.push(wall('exitGate',0,-23,48,.8));return r;}
 blocked(x,y,z){const [bx,bz]=this.config.bounds;if(Math.abs(x)>bx-.4||Math.abs(z)>bz-.4)return true;return [...this.config.walls,...this.gates()].some(w=>y<w.y+w.h-.08&&inside(x,z,w,.32));}
 groundAt(x,z,max=100){return this.floors().filter(r=>inside(x,z,r,.1)&&r.y<=max).sort((a,b)=>b.y-a.y)[0];}
 visible(a,b){const n=Math.ceil(dist(a,b)*3);for(let i=1;i<n;i++){const t=i/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;if([...this.config.walls,...this.gates()].some(w=>w.h>1.4&&inside(x,z,w)))return false;}return true;}
 objectActive(o){const f=this.flags;if(o.type==='relic')return !this.relics[this.level];if(o.type==='plate')return !(['seal0','seal1'].includes(o.id)&&f.seals);if(o.id==='tideWheel')return !f.rope;if(o.id.startsWith('torch'))return !f['rune'+o.id.slice(-1)];if(o.id==='shield'||o.id==='stormbow')return f.trialDone&&!f[o.id];if(o.id==='raft')return f.rope&&f.chart&&!f.raft;return !f[o.id];}
 target(p){return this.config.objects.filter(o=>this.objectActive(o)&&(o.role<0||o.role===p.id)&&o.type!=='plate'&&dist(p,o)<(['chain','rune'].includes(o.type)?15:2.9)&&Math.abs(p.y-o.y)<2.3&&this.visible(p,o)).sort((a,b)=>dist(p,a)-dist(p,b))[0];}
 setFlag(id,value=true){this.flags[id]=value;this.emit('progress',null,{id});}
 nearbyThreat(o,range=7){return this.enemies.some(e=>e.hp>0&&dist(e,o)<range&&!e.stun);}
 use(i){const p=this.players[i];if(p.down||p.cool>0)return;p.cool=.42;p.action=.35;const o=this.target(p),f=this.flags;
 if(o){const id=o.id;if(o.type==='relic'){this.relics[this.level]=true;this.emit('relic','找到航海日志碎页 '+Object.keys(this.relics).length+'/'+stages.length);return;}
 if(o.type==='key'||o.type==='alarm'){if(this.nearbyThreat(o)){this.emit('hint','守卫盯着这里！请烁投诱饵引开，或先击倒守卫。');return;}this.setFlag(id);this.emit('mechanism',o.type==='key'?'钥匙到手！两人到末端印记会合。':'警报已拆除。寻找下一处红色装置。');}
 else if(o.type==='lever'||o.type==='winch'||o.type==='debris'){if(o.id==='winch1'&&p.y<1.5){this.emit('hint','绞盘在高台上：跳上三层齿轮台阶。');return;}this.setFlag(id);this.emit('mechanism',o.type==='lever'?'同伴的牢门打开了。':o.type==='winch'?'桥梁已锁紧，同伴现在可以过桥。':'碎石已击碎！另一人射断吊链。');if(o.type==='winch')this.checkpointAll(0,id==='winch0'?-8:-27);}
 else if(o.type==='chain'||o.type==='rune'){this.shoot(p,o,'object');return;}
 else if(o.type==='wheel'){f.tideUntil=this.t+18;this.emit('mechanism','潮门打开18秒！烁进入西边岩洞取绳索。');}
 else if(o.type==='rope'){if(!(f.tideUntil>this.t)){this.emit('hint','请岚先转动潮门，释放绳索锁扣。');return;}this.setFlag(id);this.emit('mechanism','绳索到手，潮门保持开启。');}
 else if(o.type==='chart'){if(!f.weight){this.emit('hint','海图卡在残骸中：烁需要踩住东侧配重盘。');return;}this.setFlag(id);this.emit('mechanism','拿到海图！带着绳索回到中央码头。');}
 else if(o.type==='raft'){this.setFlag(id);this.checkpointAll(0,-15);this.emit('mechanism','浮桥已装好！一起走向远处遗迹。');}
 else if(o.type==='torch'){const n=+id.slice(-1);if(n>0&&!f['rune'+(n-1)]){this.emit('hint','先完成前一组月火与符文。');return;}f['light'+n]=this.t+12;this.emit('mechanism','第'+(n+1)+'枚符文亮起12秒，岚射中同号符文！');}
 else if(o.type==='shield'||o.type==='stormbow'){this.setFlag(id);this.emit('mechanism',o.type==='shield'?'烁获得风暴盾：可以反击潮王震波。':'岚获得风暴弓：可以穿透潮王核心。');}
 return;}
 if(i===0){if(p.mode===1){const d={x:p.x-Math.sin(p.yaw)*7,z:p.z-Math.cos(p.yaw)*7,life:8};if(this.blocked(d.x,0,d.z)){d.x=p.x-Math.sin(p.yaw)*3;d.z=p.z-Math.cos(p.yaw)*3;}this.decoys.push(d);this.emit('decoy','诱饵发出声响，附近守卫正在靠近它。');p.cool=1.2;}else{p.shield=this.level===7?4:3.2;p.cool=.8;for(const e of this.enemies)if(e.hp>0&&dist(p,e)<3.4){e.armor=false;e.stun=2;e.hp-=1;if(e.hp<=0)this.kill(e);}this.emit('shield','举盾3秒；近身盾击可以剥开重甲。');}}
 else{if(p.mode===1){this.flags.scanUntil=this.t+6;this.emit('scan','望远镜已标记远处目标。按Backspace切回弓箭射击。');return;}let targets=this.enemies.filter(e=>e.hp>0&&dist(p,e)<17&&this.visible(p,e)).sort((a,b)=>dist(p,a)-dist(p,b));const boss=this.level===7&&this.boss.hp>0&&this.boss.weak>0&&dist(p,this.boss)<22?this.boss:null;if(boss)this.shoot(p,boss,'boss');else if(targets[0])this.shoot(p,targets[0],'enemy');else{this.emit('hint','没有射程内可见目标。靠近敌人，或走到机关旁按使用。');p.cool=.18;}}
 }
 shoot(p,target,kind){this.shots.push({x:p.x,y:p.y+1,z:p.z,tx:target.x,ty:kind==='boss'?3:target.y||1,tz:kind==='boss'?target.z+2.4:target.z,kind,id:target.id,life:2});this.emit('shot');p.cool=.48;}
 hit(s){if(s.kind==='object'){const o=this.config.objects.find(o=>o.id===s.id);if(o.type==='rune'){const n=+o.id.slice(-1);if(!(this.flags['light'+n]>this.t)){this.emit('hint','符文还未被照亮。请烁点燃左路同号月火。');return;}}this.setFlag(s.id);this.emit('mechanism','命中！机关已解开。');}else if(s.kind==='enemy'){const e=this.enemies.find(e=>e.id===s.id);if(e&&e.hp>0){if(e.armor){this.emit('hint','箭被重甲挡住！烁靠近用盾击破甲。');return;}e.hp-=1;e.stun=.3;if(e.hp<=0)this.kill(e);else this.emit('hit');}}else if(s.kind==='boss'&&this.boss.weak>0){this.boss.hp=Math.max(0,this.boss.hp-1);this.boss.windowHits=(this.boss.windowHits||0)+1;if(this.boss.windowHits>=3){this.boss.weak=0;this.boss.state='idle';this.boss.timer=4.5;}this.emit('hit');if(this.boss.hp<=0){this.setFlag('bossDead');this.enemies=[];this.emit('victory','潮王倒下了！两人一起登上北边灯塔，点亮归航的光。');}else this.boss.phase=this.boss.hp>12?1:this.boss.hp>6?2:3;}}
 kill(e){e.hp=0;e.dead=this.level>=6?99999:16;e.alert=false;this.emit('enemyDown');}
 checkpointAll(x,z){for(const p of this.players)p.checkpoint={x:x+(p.id?1.2:-1.2),y:0,z};}
 hurt(p,damage=1){if(p.inv>0||p.down>0)return;if(p.shield>0){this.emit('block');return;}p.hp-=damage;p.inv=1.4;this.emit('hurt',(p.id?'岚':'烁')+'受伤 '+Math.max(0,p.hp)+'/5');if(p.hp<=0)this.recover(p);}
 recover(p){if(p.down)return;p.down=1.6;p.vy=0;this.recoveries++;this.emit('rescue',(p.id?'玩家2 岚':'玩家1 烁')+'将在最近路标复起；已解机关保留。');if(this.level===3)this.fog=Math.max(this.fog,p.checkpoint.z+17);}
 spawnWave(){const n=this.flags.wave||0;this.enemies=[];for(let i=0;i<n+2;i++)this.enemies.push(this.enemy('wave'+n+'-'+i,(i%2?1:-1)*(4+Math.floor(i/2)*5),-7-Math.floor(i/2)*6,0,0,true));this.emit('wave','第 '+(n+1)+'/3 波重甲守卫：先盾击破甲，再用箭收尾。');}
 puzzle(){const f=this.flags,p=this.players,on=(i,id)=>{const o=this.config.objects.find(o=>o.id===id);return o&&p[i].down<=0&&p[i].ground&&dist(p[i],o)<1.65;};
 if(this.level===0&&!f.seals&&f.key&&on(0,'seal0')&&on(1,'seal1')){this.setFlag('seals');this.emit('mechanism','双印记共鸣，大门打开。');}
 if(this.level===1&&!f.seals&&[0,1,2].every(i=>f['alarm'+i])&&on(0,'seal0')&&on(1,'seal1')){this.setFlag('seals');this.emit('mechanism','警报静默，长厅出口打开。');}
 if(this.level===2){f.hold0=on(0,'bridgePlate0');f.hold1=on(1,'bridgePlate1');}
 if(this.level===3){if(!f.running&&p.every(a=>a.z<38))this.setFlag('running');for(let i=0;i<3;i++)if(f['debris'+i]&&f['chain'+i]&&!f['cp'+i]){this.setFlag('cp'+i);this.checkpointAll(0,23-i*21);}}
 if(this.level===4)f.weight=on(0,'counterweight');
 if(this.level===6){if(!f.trial&&on(0,'trial0')&&on(1,'trial1')){this.setFlag('trial');this.spawnWave();}if(f.trial&&!f.trialDone&&this.enemies.every(e=>e.hp<=0)){f.wave=(f.wave||0)+1;if(f.wave>=3){this.setFlag('trialDone');this.emit('mechanism','试炼完成！分别领取风暴盾与风暴弓。');}else this.spawnWave();}}
 }
 tick(dt,held={},pressed={}){if(this.finished)return;this.t+=dt;this.puzzle();for(const p of this.players){const k=this.bindings[p.id];p.cool=Math.max(0,p.cool-dt);p.shield=Math.max(0,p.shield-dt);p.inv=Math.max(0,p.inv-dt);p.action=Math.max(0,p.action-dt);if(p.down>0){p.down-=dt;if(p.down<=0){Object.assign(p,p.checkpoint);p.down=0;p.hp=5;p.inv=2;p.ground=true;}continue;}
 if(pressed[k.switch]){p.mode=1-p.mode;this.emit('switch',(p.id?'岚':'烁')+'：'+(p.id?(p.mode?'望远镜侦察':'弓箭 / 机关工具'):p.mode?'诱饵':'盾牌'));}if(pressed[k.use]||(p.id===1&&(pressed.NumpadEnter||pressed.ControlRight)))this.use(p.id);
 p.yaw+=((held[k.camL]?1:0)-(held[k.camR]?1:0))*dt*1.8;let x=(held[k.right]?1:0)-(held[k.left]?1:0),z=(held[k.down]?1:0)-(held[k.up]?1:0),n=Math.hypot(x,z);if(n>1){x/=n;z/=n;}const dx=x*Math.cos(p.yaw)+z*Math.sin(p.yaw),dz=-x*Math.sin(p.yaw)+z*Math.cos(p.yaw);p.moving=n?1:0;if(n)p.face=Math.atan2(-dx,-dz);if(pressed[k.jump]&&p.ground){p.vy=8.4;p.ground=false;this.emit('jump');}
 const speed=p.shield>0?4.6:5.8,ox=p.x,oz=p.z;if(!this.blocked(p.x+dx*speed*dt,p.y,p.z))p.x+=dx*speed*dt;if(!this.blocked(p.x,p.y,p.z+dz*speed*dt))p.z+=dz*speed*dt;for(const r of this.floors())if(r.y>p.y+.16&&inside(p.x,p.z,r,.2)){p.x=ox;p.z=oz;}
 const oy=p.y;p.vy-=22*dt;p.y+=p.vy*dt;const floor=this.floors().filter(r=>inside(p.x,p.z,r,.08)&&p.vy<=0&&oy>=r.y-.04&&p.y<=r.y+.04).sort((a,b)=>b.y-a.y)[0];if(floor){p.y=floor.y;p.vy=0;p.ground=true;}else p.ground=false;if(p.y<-5)this.recover(p);
 }
 this.puzzle();this.updateEnemies(dt);this.updateBoss(dt);if(this.level===3&&this.flags.running){this.fog-=dt*2.3;for(const p of this.players)if(p.z>this.fog)this.hurt(p,5);}
 for(const d of this.decoys)d.life-=dt;this.decoys=this.decoys.filter(d=>d.life>0);
 for(const s of this.shots){s.life-=dt;const dx=s.tx-s.x,dy=s.ty-s.y,dz=s.tz-s.z,n=Math.hypot(dx,dy,dz);if(n<dt*24+.2){this.hit(s);s.life=0;}else{s.x+=dx/n*24*dt;s.y+=dy/n*24*dt;s.z+=dz/n*24*dt;}}this.shots=this.shots.filter(s=>s.life>0);
 const [ex,ez]=this.config.exit;if(this.ready()&&this.players.every(p=>!p.down&&p.ground&&Math.hypot(p.x-ex,p.z-ez)<3))this.finish+=dt;else this.finish=0;if(this.finish>.8){this.finished=true;this.emit('complete');}
 }
 updateEnemies(dt){for(const e of this.enemies){if(e.hp<=0){e.dead-=dt;if(e.dead<=0){e.hp=e.max;e.x=e.homeX;e.z=e.homeZ;e.armor=false;}continue;}e.attack-=dt;e.stun=Math.max(0,e.stun-dt);if(e.stun>0)continue;let aim=null;const decoy=this.decoys.find(d=>dist(e,d)<25);if(decoy){aim=decoy;e.alert=true;}else{let ps=this.players.filter(p=>!p.down&&dist(p,e)<15&&this.visible(e,p)).sort((a,b)=>dist(a,e)-dist(b,e));if(ps.length){aim=ps[0];e.alert=true;e.target=aim.id;}else e.alert=false;}
 if(!aim){aim={x:e.homeX+Math.sin(this.t*.45+e.homeX)*e.patrol*3,z:e.homeZ+Math.cos(this.t*.4)*e.patrol*3};}
 const d=dist(e,aim),speed=e.alert?2.7:1.25;if(d>.9){const dx=(aim.x-e.x)/d,dz=(aim.z-e.z)/d;e.face=Math.atan2(-dx,-dz);if(!this.blocked(e.x+dx*dt*speed,0,e.z))e.x+=dx*dt*speed;if(!this.blocked(e.x,0,e.z+dz*dt*speed))e.z+=dz*dt*speed;}
 if(e.alert&&!decoy&&d<1.5&&e.attack<=0){this.hurt(aim);e.attack=1.4;if(aim.shield>0){e.stun=1;e.armor=false;}}
 }}
 updateBoss(dt){if(this.level!==7||this.boss.hp<=0)return;if(!this.flags.battle){if(this.players.every(p=>p.z<12)){this.flags.battle=true;this.checkpointAll(0,6);}else return;}const b=this.boss;b.timer-=dt;b.weak=Math.max(0,b.weak-dt);if(b.ring>=0){b.ring+=dt*9;for(const p of this.players)if(Math.abs(dist(p,b)-b.ring)<.7&&p.y<.8)this.hurt(p);if(b.ring>32)b.ring=-1;}
 if(b.state==='idle'&&b.timer<=0){b.state='warn';b.timer=2.5;this.emit('warning','潮王蓄力！烁靠近核心前方举盾；岚拉开距离，准备射击。');}
 else if(b.state==='warn'&&b.timer<=0){b.ring=0;b.cycle++;const p=this.players[0];if(!p.down&&p.shield>0&&dist(p,b)<9){b.weak=6;b.windowHits=0;b.state='open';b.timer=6;this.emit('weak','风暴盾反击成功！核心暴露6秒，岚连续点按 Enter！');}else{b.state='idle';b.timer=4;this.emit('warning','核心仍在护甲中。下一次蓄力时，烁要靠近并举盾。');}if(b.phase>=2){for(let i=0;i<b.phase-1&&this.enemies.filter(e=>e.hp>0).length<4;i++)this.enemies.push(this.enemy('add'+b.cycle+'-'+i,(i?1:-1)*12,3,0,1));}}
 else if(b.state==='open'&&b.timer<=0){b.state='idle';b.timer=4.5;}
 if(b.phase===3&&Math.floor(this.t/5)>Math.floor((this.t-dt)/5)){const p=this.players[1];this.effects.push({type:'rock',x:p.x,z:p.z,time:1.8});this.emit('warning','地面红圈要落石了，岚离开红圈！');}
 for(const e of this.effects){e.time-=dt;if(e.time<=0){for(const p of this.players)if(dist(p,e)<2.2)this.hurt(p,2);}}this.effects=this.effects.filter(e=>e.time>0);
 }
 ready(){const f=this.flags;return [f.key&&f.seals,f.seals,f.winch0&&f.winch1,[0,1,2].every(i=>f['debris'+i]&&f['chain'+i]),f.raft,[0,1,2].every(i=>f['rune'+i]),f.shield&&f.stormbow,f.bossDead][this.level]||false;}
 objective(i){const f=this.flags;let id;if(this.level===0)id=!f['release'+i]?'release'+i:!f.key?(i===0?'key':'key'):'seal'+i;if(this.level===1){id=[0,1,2].map(n=>'alarm'+n).find(n=>!f[n])||'seal'+i;}if(this.level===2)id=!f.winch0?(i?'winch0':'bridgePlate0'):!f.winch1?(i?'bridgePlate1':'winch1'):null;if(this.level===3){const n=[0,1,2].find(n=>!f['debris'+n]||!f['chain'+n]);if(n!==undefined)id=(i?'chain':'debris')+n;}if(this.level===4)id=!f.rope?(i?'tideWheel':'rope'):!f.chart?(i?'chart':'counterweight'):!f.raft?'raft':null;if(this.level===5){const n=[0,1,2].find(n=>!f['rune'+n]);if(n!==undefined)id=(i?'rune':'torch')+n;}if(this.level===6)id=!f.trial?'trial'+i:f.trialDone?(i?'stormbow':'shield'):null;if(this.level===7&&!f.bossDead)return{x:this.boss.x,z:this.boss.z,id:'boss',type:'boss'};return this.config.objects.find(o=>o.id===id)||{x:this.config.exit[0],z:this.config.exit[1],id:'exit',type:'exit'};}
 status(){const f=this.flags;switch(this.level){case 0:return '牢门 '+[f.release0,f.release1].filter(Boolean).length+'/2 · 钥匙 '+(f.key?'已取':'未取')+' · 双印 '+(f.seals?'完成':'待会合');case 1:return '警报 '+[0,1,2].filter(i=>f['alarm'+i]).length+'/3 · 双印 '+(f.seals?'完成':'待会合');case 2:return '第一桥 '+(f.winch0?'锁定':f.hold0?'踩住':'未开')+' · 第二桥 '+(f.winch1?'锁定':f.hold1?'踩住':'未开');case 3:return '道路 '+[0,1,2].filter(i=>f['debris'+i]&&f['chain'+i]).length+'/3 · 黑潮在身后';case 4:return '绳索 '+(f.rope?'✓':'○')+' · 海图 '+(f.chart?'✓':'○')+' · 浮桥 '+(f.raft?'✓':'○');case 5:return '月纹 '+[0,1,2].filter(i=>f['rune'+i]).length+'/3';case 6:return f.trialDone?'试炼完成 · 分别领取风暴装备':'重甲试炼 '+Math.min(3,(f.wave||0)+1)+'/3 波';case 7:return '潮王 '+this.boss.hp+'/18 · 阶段 '+this.boss.phase+'/3'+(this.boss.weak>0?' · 核心暴露！':'');}}
}
(typeof module!=='undefined'?require('./deep-sea.js'):root.installDeepSea)(Adventure,stages);
const api={Adventure,stages,keys,inside,dist};if(typeof module!=='undefined')module.exports=api;else root.Tidebound=api;
})(typeof window!=='undefined'?window:globalThis);



