'use strict';
const {Adventure,stages,keys,dist}=Tidebound,$=id=>document.getElementById(id),canvas=$('scene');
let saved={level:0,max:0,flags:{},relics:{},muted:false,volume:.45};try{const s=JSON.parse(localStorage.getItem('tideborn.coop.v1'));if(s&&Number.isInteger(s.level))saved={...saved,...s,level:Math.max(0,Math.min(7,s.level))};}catch{}
const game=new Adventure(saved.level);game.relics=saved.relics||{};if(Array.isArray(saved.bindings)&&saved.bindings.length===2)game.bindings=saved.bindings;
let mode='menu',held={},pressed={},time=0,last=performance.now(),acc=0,uiTick=0,muted=saved.muted,volume=saved.volume,audio=null,toastUntil=0,storyPage=0,rebind=null;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setScissorTest(true);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xc5e4ea,0x303442,2.1));const sun=new THREE.DirectionalLight(0xffd9a1,2.4);sun.position.set(-15,35,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:60,bottom:-60});sun.shadow.normalBias=.03;scene.add(sun);
const cameras=[0,1].map(()=>new THREE.PerspectiveCamera(67,innerWidth/2/innerHeight,.12,150));
const world=new THREE.Group(),dynamic=new THREE.Group(),fx=new THREE.Group();scene.add(world,dynamic,fx);const mats={};
const mat=c=>mats[c]||(mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.82}));
function mesh(g,geo,c,x=0,y=0,z=0){const m=new THREE.Mesh(geo,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
const box=(g,x,y,z,w,h,d,c)=>mesh(g,new THREE.BoxGeometry(w,h,d),c,x,y,z);
function ball(g,x,y,z,rx,ry,rz,c){const m=mesh(g,new THREE.SphereGeometry(1,12,9),c,x,y,z);m.scale.set(rx,ry,rz);return m;}
const cyl=(g,x,y,z,r,h,c)=>mesh(g,new THREE.CylinderGeometry(r,r,h,12),c,x,y,z);
function ring(g,x,y,z,r,c,t=.06){const m=mesh(g,new THREE.TorusGeometry(r,t,6,28),c,x,y,z);m.rotation.x=-Math.PI/2;return m;}
function rod(g,a,b,r,c){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),v=vb.clone().sub(va),m=cyl(g,(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2,r,v.length(),c);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m;}
function clear(g){for(const o of [...g.children]){g.remove(o);o.traverse(m=>{if(m.geometry)m.geometry.dispose();});}}
function person(id,enemy=false){const g=new THREE.Group(),c=enemy?0x59626a:id?0x3a9e9b:0xd39049,skin=enemy?0x858e86:0xcda886;ball(g,0,1,0,.32,.43,.22,c);box(g,0,.65,0,.52,.15,.36,0x3b424d);ball(g,0,1.63,0,.25,.3,.24,skin);ball(g,0,1.78,.035,.28,.17,.25,enemy?0x454e5e:id?0x1e6572:0x8d523c);if(!enemy){box(g,0,1.37,.23,.56,.62,.06,id?0x245967:0xb3663a);box(g,-.3,1.2,.2,.08,.8,.14,id?0x6adad1:0xefbe76);for(let j=0;j<3;j++)box(g,0,1.12-j*.12,-.23,.3,.025,.025,0xe3ca93);}for(const x of [-.09,.09])ball(g,x,1.64,-.23,.03,.03,.02,0x162b36);const limbs=[];for(const x of [-.16,.16]){const l=new THREE.Group();l.position.set(x,.63,0);g.add(l);cyl(l,0,-.22,0,.095,.48,0x334d59);box(l,0,-.49,-.08,.22,.15,.37,0x303b48);limbs.push(l);}for(const x of [-.38,.38]){const arm=new THREE.Group();arm.position.set(x,1.25,0);g.add(arm);cyl(arm,0,-.24,0,.08,.48,c);ball(arm,0,-.48,0,.09,.11,.09,skin);limbs.push(arm);}
const tool=new THREE.Group();g.add(tool);if(!enemy&&!id){box(tool,-.46,.96,-.19,.48,.72,.12,0xc6a271);box(tool,-.46,.99,-.27,.1,.5,.035,0x77c8d3);}else if(!enemy){const bow=mesh(tool,new THREE.TorusGeometry(.4,.035,6,20,Math.PI),0xd8c18c,.43,1,-.17);bow.rotation.z=Math.PI/2;rod(tool,[.43,.6,-.17],[.43,1.4,-.17],.009,0xe2d6b0);}else{box(tool,.42,.75,-.22,.12,.85,.1,0x96a8ab);box(g,0,1.64,-.265,.42,.12,.025,0x243544);}
const aura=ring(g,0,.03,0,.47,enemy?0xc67568:id?0x5bd9ce:0xedb877,.035);return{g,limbs,tool,aura};}
const actors=[person(0),person(1)];actors.forEach(a=>scene.add(a.g));
let enemyModels=new Map(),objectModels=new Map(),labels=[],floorGroup=new THREE.Group(),gateGroup=new THREE.Group(),floorKey='',gateKey='',bossModel=null,bossArms=[],beacons=[],fogWall=null,ringModel=null,occluders=[];
function addLabel(g,text,kind='object'){const els=[0,1].map(()=>{const e=document.createElement('div');e.className='label';e.textContent=text;$('labels').appendChild(e);return e;});labels.push({g,text,kind,els});}
const names={release0:'给烁开牢门',release1:'给岚开牢门',key:'守卫钥匙',seal0:'岚的会合印',seal1:'烁的会合印',bridgePlate0:'岚留守 · 第一桥',bridgePlate1:'烁留守 · 第二桥',winch0:'烁锁紧第一桥',winch1:'岚登台锁桥',tideWheel:'烁转动潮门',rope:'岚取绳索',counterweight:'岚踩住配重',chart:'烁取海图',raft:'修复浮桥',trial0:'岚的试炼印',trial1:'烁的试炼印',shield:'风暴盾 · 岚',stormbow:'风暴弓 · 烁',relic:'航海日志碎页',boss:'潮王核心',exit:'两人一起到达'};
function objectName(o){return names[o.id]||(o.type==='alarm'?'警报 '+(+o.id.slice(-1)+1):o.type==='torch'?'月火 '+(+o.id.slice(-1)+1):o.type==='rune'?'符文 '+(+o.id.slice(-1)+1):o.type==='debris'?'岚击碎路障':'烁射断吊链');}
function makeObject(o){const g=new THREE.Group(),color=o.role===0?0xedaf6f:o.role===1?0x6bd5d0:0xeed7a0;g.position.set(o.x,o.y,o.z);ring(g,0,.04-o.y,0,o.type==='plate'?1.45:.8,color,.065);
if(o.type==='plate'){cyl(g,0,.05,0,1.3,.1,0x596c70);ring(g,0,.13,0,.9,color,.06);for(let a=0;a<4;a++)box(g,Math.sin(a*Math.PI/2)*.65,.13,Math.cos(a*Math.PI/2)*.65,.16,.04,.16,color);}
else if(['lever','winch','wheel'].includes(o.type)){box(g,0,.6,0,1.1,1.2,.9,0x61767b);const wheel=ring(g,0,1.35,-.52,.48,color,.09);wheel.rotation.x=Math.PI/2;box(g,0,1.35,-.53,.09,.85,.09,color);box(g,0,1.35,-.53,.85,.09,.09,color);}
else if(o.type==='torch'){cyl(g,0,.65,0,.4,1.3,0x586678);ball(g,0,1.7,0,.27,.48,.27,0xefc06a);}
else if(['rune','alarm'].includes(o.type)){box(g,0,.45,0,1,.8,.7,0x3f5362);const crystal=mesh(g,new THREE.OctahedronGeometry(.45),o.type==='alarm'?0xd77469:color,0,1,0);}
else if(o.type==='debris'){for(let j=0;j<7;j++){const m=mesh(g,new THREE.DodecahedronGeometry(.65),0x727d82,Math.sin(j)*.75,.45+j%2*.5,Math.cos(j)*.5);m.rotation.set(j*.7,j,0);}}
else if(o.type==='chain'){cyl(g,0,1,0,.08,2,0xb4beb0);for(let j=0;j<4;j++){const r=ring(g,0,.3+j*.4,0,.19,color,.065);r.rotation.x=0;r.rotation.y=j%2*Math.PI/2;}}
else if(o.type==='raft'){for(let i=0;i<5;i++)box(g,-1+i*.5,.18,0,.4,.3,2.5,0x9e8055);}
else if(o.type==='rope'){for(let j=0;j<5;j++)ring(g,0,.2+j*.06,0,.45,0xe5c98d,.05);}
else if(o.type==='shield'){box(g,0,1,0,.8,1.1,.15,0xbad5d1);ball(g,0,1,-.15,.17,.3,.1,0x69ccdc);}
else if(o.type==='stormbow'){const b=ring(g,0,1,0,.6,0x91d9d4,.07);b.rotation.x=0;box(g,0,1,0,.05,1.2,.05,0xf2dca6);}
else{box(g,0,.6,0,.6,.15,.7,0xedcd8d);box(g,0,.65,0,.4,.04,.55,0x809896);}
objectModels.set(o.id,g);dynamic.add(g);addLabel(g,objectName(o));}
const palettes={prison:[0x1d3546,0x687578,0x83918d],hall:[0x213b45,0x768580,0x9ca692],tower:[0x263c52,0x6e8090,0xadb3a1],chase:[0x33404a,0x747771,0xaa9c80],coast:[0x85bbc8,0xd4c29b,0xe9d5a0],ruins:[0x426b75,0x778e83,0xa9b59b],armory:[0x30485d,0x687d8b,0xb3ae95],boss:[0x2c5364,0x788f92,0x98ada9]};
function drawFloors(){const fs=game.floors(),key=fs.map(f=>f.id).join('|');if(key===floorKey)return;floorKey=key;clear(floorGroup);const colors=palettes[game.config.theme];for(const f of fs){box(floorGroup,f.x,f.y-.4,f.z,f.w,.8,f.d,f.id.includes('bridge')||f.id==='raftBridge'?0xa58a64:colors[1]);box(floorGroup,f.x,f.y-.05,f.z,f.w,.1,f.d,colors[2]);if(f.w>10)for(let z=-f.d/2+2;z<f.d/2;z+=4){box(floorGroup,f.x,f.y+.006,f.z+z,f.w,.012,.035,colors[1]);}if(f.d<12&&f.w<6)for(let z=-f.d/2+.3;z<f.d/2;z+=.7)box(floorGroup,f.x,f.y+.04,f.z+z,f.w,.09,.12,0x6b6253);}}
function drawGates(){const gs=game.gates(),key=gs.map(g=>g.id).join('|');if(key===gateKey)return;gateKey=key;clear(gateGroup);for(const g of gs){const group=new THREE.Group();group.position.set(g.x,0,g.z);for(let x=-g.w/2+.3;x<g.w/2;x+=1.1)box(group,x,1.65,0,.16,3.3,.2,0x698187);box(group,0,3.25,0,g.w,.28,.4,0xb3a17b);box(group,0,.4,0,g.w,.17,.2,0x84959a);gateGroup.add(group);}}
function wallMesh(w){const colors=palettes[game.config.theme],m=box(world,w.x,w.h/2,w.z,w.w,w.h,w.d,colors[1]);occluders.push(m);box(world,w.x,w.h+.08,w.z,w.w+.15,.16,w.d+.15,colors[2]);if(w.h>2){for(let y=.65;y<w.h;y+=.7)box(world,w.x,y,w.z-w.d/2-.011,w.w,.026,.026,0x53696d);}}
function palm(x,z){const h=4.5;rod(world,[x,0,z],[x+.6,h,z],.19,0x93775c);for(let i=0;i<7;i++){const a=i*Math.PI*2/7,m=ball(world,x+.6+Math.sin(a)*1.1,h-.15,z+Math.cos(a)*1.1,.4,.13,1.6,0x5e9875);m.rotation.y=a;m.rotation.z=.18;}}
function makeBoss(){const g=new THREE.Group();ball(g,0,2.7,0,3.1,2.6,2.4,0x446973);ball(g,0,3.1,-.45,2.6,2.1,2.4,0x748d87);ball(g,0,4.8,-.4,1.45,1.15,1.2,0x8caaa0);for(const x of [-.65,.65]){ball(g,x,4.95,-1.51,.23,.15,.1,0xf0b172);mesh(g,new THREE.ConeGeometry(.35,1.3,5),0xe3d4b0,x*2,5.7,-.4);}box(g,0,4.25,-1.45,1.3,.18,.15,0x183a48);const core=mesh(g,new THREE.OctahedronGeometry(.85),0x68d9df,0,3,-2.5);g.userData.core=core;bossArms=[];for(const x of [-3,3]){const a=new THREE.Group();a.position.set(x,3.2,0);g.add(a);ball(a,0,-1,0,.85,1.5,.8,0x6b8a84);ball(a,0,-2.1,-.4,1,.6,1,0x8ca79a);bossArms.push(a);ball(g,x*.55,.8,.6,.9,.8,1.2,0x5b7c80);}for(let i=0;i<8;i++){const a=i/8*Math.PI*2,m=mesh(g,new THREE.ConeGeometry(.4,1.6,5),0xa6b8a0,Math.sin(a)*2.2,3.5+Math.cos(a)*.4,Math.cos(a)*2);m.rotation.x=Math.cos(a)*.6;m.rotation.z=-Math.sin(a)*.6;}g.position.set(0,0,-10);g.rotation.y=Math.PI;dynamic.add(g);addLabel(g,'潮王 · 岚举盾反击 / 烁射核心');return g;}
function build(){for(const l of labels)l.els.forEach(e=>e.remove());labels=[];clear(world);clear(dynamic);clear(fx);enemyModels=new Map();objectModels=new Map();occluders=[];floorGroup=new THREE.Group();gateGroup=new THREE.Group();world.add(floorGroup,gateGroup);floorKey='';gateKey='';drawFloors();drawGates();const colors=palettes[game.config.theme];scene.background=new THREE.Color(colors[0]);scene.fog=new THREE.Fog(colors[0],30,95);game.config.walls.forEach(wallMesh);
const [bx,bz]=game.config.bounds,outside=['coast','boss','ruins'].includes(game.config.theme);if(!outside){for(const x of [-bx,bx])wallMesh({x,z:0,w:1,d:bz*2,h:5});for(const z of [-bz,bz])wallMesh({x:0,z,w:bx*2,d:1,h:5});for(let z=-bz+4;z<bz;z+=8)for(const x of [-bx+1,bx-1]){box(world,x,1.8,z,.7,3.6,.9,colors[1]);ball(world,x*.96,2.6,z,.15,.3,.15,0xefbc70);}}
else{box(world,0,-1.6,0,180,.1,180,game.config.theme==='coast'?0x4b99af:0x315e73);for(let j=0;j<16;j++){const x=(j%2?-1:1)*(bx+2+(j%3)),z=-bz+j*bz/8;const r=mesh(world,new THREE.DodecahedronGeometry(2.2),0x607e81,x,-.2,z);r.scale.y=1.6;if(game.config.theme==='coast'&&j%2)palm(x*.8,z);}}
if(game.level===2){box(world,0,-7,0,80,.2,110,0x172c41);for(let j=0;j<6;j++){const gear=ring(world,j%2?-12:12,3,-26+j*10,1.6,0xaa9673,.22);gear.rotation.x=0;}}
game.config.objects.forEach(makeObject);const ex=new THREE.Group();ex.position.set(game.config.exit[0],0,game.config.exit[1]);for(const x of [-2,2])box(ex,x,1.8,0,.35,3.6,.5,0xd3c69f);box(ex,0,3.7,0,4.6,.35,.6,0xd3c69f);ring(ex,0,.03,0,2.5,0x9ed9c4,.08);dynamic.add(ex);addLabel(ex,'两人一起到达');
dressRegion();actors.forEach((a,i)=>addLabel(a.g,'玩家'+(i+1)+' · '+(i?'烁':'岚'),'player'));
beacons=[0,1].map(i=>{const g=new THREE.Group();cyl(g,0,2,0,.055,4,i?0x7bebe1:0xffce81);const gem=mesh(g,new THREE.OctahedronGeometry(.25),i?0x7bebe1:0xffce81,0,4.2,0);dynamic.add(g);return g;});
fogWall=null;if(game.level===3){fogWall=new THREE.Group();for(let i=0;i<12;i++)ball(fogWall,-13+i*2.4,1.5,0,2,3.5,1.5,0x192a39);dynamic.add(fogWall);}
bossModel=game.level===7?makeBoss():null;ringModel=ring(dynamic,0,.12,-10,1,0xe9b572,.08);ringModel.visible=false;
for(let i=0;i<2;i++){const p=game.players[i];cameras[i].position.set(p.x,3.4,p.z+6);}updateUI();}
function keyName(k){return({KeyW:'W',KeyA:'A',KeyS:'S',KeyD:'D',KeyX:'X',KeyQ:'Q',KeyE:'E',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',Space:'空格',ShiftLeft:'左Shift',ControlLeft:'左Ctrl',Enter:'Enter',Backspace:'Backspace',Comma:',',Period:'.'}[k]||k.replace('Key',''));}
function updateUI(){$('region').textContent=game.config.name+' · '+game.config.subtitle;$('status').textContent=game.status();$('mute').textContent=muted?'音效 关':'音效 开';$('bossbar').hidden=game.level!==7||game.flags.bossDead;$('bossbar').querySelector('i').style.width=game.boss.hp/18*100+'%';for(let i=0;i<2;i++){const p=game.players[i],k=game.bindings[i],o=game.objective(i),d=dist(p,o),angle=Math.atan2(-(o.x-p.x),-(o.z-p.z))-p.yaw,turn=Math.atan2(Math.sin(angle),Math.cos(angle));const arrow=Math.abs(turn)<.5?'↑':Math.abs(turn)>2.5?'↓':turn>0?'←':'→';$('hp'+i).textContent=p.down?'正在复起…':'♥'.repeat(Math.max(0,p.hp))+'♡'.repeat(5-Math.max(0,p.hp));const near=game.target(p);$('goal'+i).textContent=near?keyName(k.use)+' · '+objectName(near):game.config.goal;$('guide'+i).textContent=arrow+' '+objectName(o)+' · '+Math.round(d)+'m'+(p.shield>0?' · 盾牌保护中':'');$('keys'+i).innerHTML='<b>'+(i?(p.mode?'烁 · 望远镜侦察':'烁 · 弓箭与机关'):'岚 · '+(p.mode?'诱饵':'盾牌'))+'</b>　'+[k.up,k.left,k.down,k.right].map(keyName).join(' ')+' 移动　<kbd>'+keyName(k.jump)+'</kbd> 跳跃<br><kbd>'+keyName(k.switch)+'</kbd> 切换　<kbd>'+keyName(k.use)+'</kbd> 使用　<kbd>'+keyName(k.camL)+' / '+keyName(k.camR)+'</kbd> 转镜头';}}

function dressRegion(){const theme=game.config.theme,[bx,bz]=game.config.bounds;
 if(theme==='coast'){
  // Driftwood, plants and a broken sail give the shore distinct landmarks.
  for(let j=0;j<18;j++){const x=(j%2?1:-1)*(22+j%4),z=24-Math.floor(j/2)*5;for(let k=0;k<3;k++){const leaf=mesh(world,new THREE.ConeGeometry(.13,.7,4),0x739a64,x+k*.18,.25,z);leaf.rotation.z=(k-1)*.3;}ball(world,x-1,.13,z+.6,.25,.12,.17,0xe4dec1);}
  for(const x of [14,16,18,20]){const plank=box(world,x,.5,-9,.25,1.2,5,0x685b49);plank.rotation.z=(x-17)*.08;}
  rod(world,[17,0,-9],[17,6,-9],.12,0x9c8865);const sail=mesh(world,new THREE.ConeGeometry(1.6,3,3),0xe6d7a9,17,4,-9);sail.scale.z=.08;sail.rotation.z=-.2;
  for(let z=-18;z<25;z+=5)for(const x of [-7,7]){const pebble=mesh(world,new THREE.DodecahedronGeometry(.2),0xb1a386,x+Math.sin(z),.1,z);pebble.scale.y=.4;}
 }
 if(['ruins','boss','armory'].includes(theme))for(let j=0;j<8;j++){const x=(j%2?1:-1)*(bx-3),z=-bz+7+Math.floor(j/2)*(bz*2-14)/3,h=3.5+j%3*.8;cyl(world,x,h/2,z,.6,h,0x7a9190);box(world,x,h,z,1.6,.35,1.6,0xa8b8a5);for(let k=0;k<3;k++)ring(world,x,.35+k,z,.64,0xb5c1ac,.045);}
 if(theme==='boss'){for(let r=5;r<=19;r+=7)ring(world,0,.018,-10,r,0x7b969b,.03);cyl(world,0,3,-28,1.3,6,0xadc1b2);mesh(world,new THREE.ConeGeometry(2,1.4,8),0x506d76,0,6.6,-28);ball(world,0,5.9,-28,.5,.5,.5,0xf5d993);}
 if(['prison','hall','chase'].includes(theme))for(let j=0;j<8;j++){const x=(j%2?1:-1)*(bx-2),z=-bz+7+j*(bz*2-14)/8;box(world,x,.35,z,1,.7,1,0x68757a);box(world,x,.74,z,1.1,.1,1.1,0x9aa192);if(j%2===0){box(world,x,3.1,z,.05,1.5,.9,0xa07358);box(world,x*.98,3.2,z,.06,.35,.35,0xe6c589);}}
}
const journalPages=[
 '盐牢的刻字：这座城堡曾经保护海岛。黑潮出现后，守卫关闭了所有城门。有人在石头上留下两道并排的刻痕——这里曾有另一对想回家的人。',
 '值夜人的便条：钟声不是号令，而是求援。拆掉警报，别让恐惧把所有人都留在走廊里。',
 '修桥匠的图纸：每座桥都留着一个需要别人踩住的开关。修桥匠说，这不是故障，这是让我们学会接应的办法。',
 '风中的船票：票背写着一个约定——最后离开城堡的人，也必须有人等。黑潮没有带走这张票。',
 '船长的航线：沿着双月遗迹寻找灯塔。绳索会固定船身，海图会指出方向，但掌舵的人需要相信另一个人的眼睛。',
 '月火守护者的记录：符文不是给点火的人看的。火在此岸亮起，答案会在彼岸出现。',
 '军械师的留言：风暴盾并不能独自打败潮王，风暴弓也无法独自打开它的核心。我把它们交给能为彼此创造机会的人。',
 '灯塔日记的末页：潮王原是海湾的守护者。让失控的风暴平息，灯塔便会重新记起每一艘船的名字。'
];
function journal(){show('<h2>海风里的八页日志</h2><p>已找到 '+Object.keys(game.relics).length+'/8 页。每区各藏一页，可以在重玩区域中继续寻找。</p><div class="grid">'+journalPages.map((p,i)=>'<div class="tile"><h3>'+stages[i].name+'</h3><p>'+(game.relics[i]?p:'尚未找到。留意岔路上的金色小册子。')+'</p></div>').join('')+'</div><div class="row"><button id="back">返回游戏</button></div>');$('back').onclick=play;}

function sound(type){if(muted||volume<=0)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=['shot','hit','hurt'].includes(type)?'triangle':'sine';const t=audio.currentTime,f={shot:220,shield:140,jump:360,mechanism:640,hurt:90,complete:900,warning:160,victory:1100,relic:760}[type]||400;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*.7,t+.16);g.gain.setValueAtTime(volume*.12,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.start();o.stop(t+.23);}catch{}}
function toast(text){if(!text)return;$('toast').textContent=text;$('toast').hidden=false;toastUntil=time+4.5;}
function save(){saved={...saved,...game.save(),bindings:game.bindings,muted,volume};try{localStorage.setItem('tideborn.coop.v1',JSON.stringify(saved));}catch{}}
function show(html,m='pause'){mode=m;held={};pressed={};$('panel').hidden=false;$('panel').innerHTML='<div class="sheet">'+html+'</div>';}
function play(){mode='play';held={};pressed={};$('panel').hidden=true;canvas.focus();}
function start(level,story=false,flags={}){game.load(level,flags);build();save();if(story){storyPage=0;storyView();}else play();}
const story=[['暴风前夜','岚与烁在送信途中遭城堡卫队扣押。窗外的黑潮正在爬上海崖——传说中沉睡的潮王，已经醒了。'],['一面盾，一张弓','岚擅长吸引守卫、抬盾挡击；烁懂机关，也能用弓命中远处目标。两人必须穿过城堡，找回失落海岸的航路。'],['让灯塔再次亮起来','遗迹中藏着能对抗潮王的风暴装备。逃出去只是开始：只有两个人一起点亮灯塔，海上的船才能找到回家的路。']];
function storyView(){const [title,text]=story[storyPage];show('<div class="eyebrow">原创双人冒险 · '+(storyPage+1)+'/3</div><h2>'+title+'</h2><p>'+text+'</p><div class="row"><button class="primary" id="nextStory">'+(storyPage===2?'进入牢房':'继续')+'</button><button id="skip">跳过剧情 · A</button></div><p class="small">左屏：玩家1 岚。右屏：玩家2 烁。各自的镜头跟在角色背后，Q/E 或逗号/句号可以转动。</p>','story');$('nextStory').onclick=()=>{if(++storyPage>=story.length)play();else storyView();};$('skip').onclick=play;}
function menu(){show('<div class="eyebrow">两名冒险者 · 两个视角 · 一次共同逃亡</div><h1>潮影双行</h1><p>从怪兽城堡的监牢出发，在追逐中逃向海岸。分头探索双月遗迹，赢取风暴装备，再一起挑战沉睡的潮王。</p><div class="grid"><div class="tile"><h3 style="color:#f5bb79">玩家1 · 岚 / 盾牌与诱饵</h3><p>WASD 移动 · X 跳跃 · Q/E 转镜头<br>左Shift 切换盾牌/诱饵 · 左Ctrl 点按使用<br>靠近机关时优先互动；远离机关再使用盾牌或诱饵。</p></div><div class="tile"><h3 style="color:#85dad3">玩家2 · 烁 / 弓箭与机关</h3><p>方向键移动 · 空格跳跃 · , / . 转镜头<br>Enter 发射 / 使用 · Backspace 切换弓箭 / 望远镜<br>不用右Ctrl、右Shift，也不用鼠标锁定。</p></div></div><div class="row"><button id="new" class="primary">新的双人冒险</button><button id="continue">继续旅程</button><button id="chapters">重玩区域</button><button id="settings">操作与音量</button><button id="journal">航海日志</button><button id="fullMenu">全屏</button></div><p class="small">八个连续区域 · 独立分屏后视镜头 · 多步协作 · 检查点复活 · 8张可选日志碎页<br>需要两位真人在同一键盘游玩。原创浏览器小游戏，不是商业原作或同等体量作品。</p>','menu');$('new').onclick=()=>start(0,true);$('continue').onclick=()=>start(saved.level,false,saved.flags);$('chapters').onclick=chapters;$('settings').onclick=settings;$('journal').onclick=journal;$('fullMenu').onclick=fullscreen;}
function chapters(){show('<h2>重走航路</h2><div class="grid">'+stages.map((s,i)=>'<button class="tile" data-stage="'+i+'" '+(i>(saved.max||0)?'disabled':'')+'><h3>'+s.name+'</h3><p>'+s.subtitle+'</p></button>').join('')+'</div><div class="row"><button id="back">返回主菜单</button></div>');document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>start(+b.dataset.stage));$('back').onclick=menu;}
function settings(){const acts={up:'前进',down:'后退',left:'左移',right:'右移',jump:'跳跃',switch:'切换',use:'使用',camL:'镜头左转',camR:'镜头右转'};show('<h2>各自的键盘与镜头</h2><p>移动方向相对自己的镜头。盾牌按一次保护3秒，诱饵按一次吸引8秒；无需按住Ctrl移动。靠近自己颜色的机关，按使用键互动。</p><div class="grid">'+[0,1].map(i=>'<div><h3>玩家'+(i+1)+' · '+(i?'烁':'岚')+'</h3><table class="rebind">'+Object.entries(acts).map(([a,label])=>'<tr><td>'+label+'</td><td><button data-bind="'+i+','+a+'">'+keyName(game.bindings[i][a])+'</button></td></tr>').join('')+'</table></div>').join('')+'</div><div class="row"><label>音量 <input id="volume" type="range" min="0" max="1" step=".05" value="'+volume+'"></label><button id="defaults">恢复默认键位</button><button id="back">返回游戏</button></div><p class="small" id="bindHelp">点按键按钮后，按一个新键；重复占用的键会被拒绝。Esc取消绑定。</p>');document.querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>{rebind=b.dataset.bind.split(',');$('bindHelp').textContent='请按新按键；Esc取消。';});$('volume').oninput=e=>{volume=+e.target.value;save();};$('defaults').onclick=()=>{game.bindings=keys.map(k=>({...k}));save();settings();};$('back').onclick=()=>{rebind=null;play();};}
function pause(){if(mode==='play'){save();show('<h2>在路标旁歇一会儿</h2><p>'+game.config.goal+'</p><p>当前：'+game.status()+'</p><div class="row"><button id="resume" class="primary">继续合作</button><button id="retry">从本区检查点重新出发</button><button id="restart">重置本区机关</button><button id="settings">操作与音量</button><button id="journal">航海日志</button><button id="chapters">重玩区域</button></div>');$('resume').onclick=play;$('retry').onclick=()=>start(game.level,false,{...game.flags});$('restart').onclick=()=>start(game.level);$('settings').onclick=settings;$('journal').onclick=journal;$('chapters').onclick=chapters;}else if(mode==='pause')play();}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('浏览器未进入全屏，可用 F11。');}}
$('fullscreen').onclick=fullscreen;$('pause').onclick=pause;$('mute').onclick=()=>{muted=!muted;save();updateUI();};
game.onEvent=e=>{if(e.type==='load')return;sound(e.type);if(e.text)toast(e.text);if(['progress','relic','mechanism'].includes(e.type))save();if(e.type==='complete'){saved.max=Math.max(saved.max||0,Math.min(7,game.level+1));save();if(game.level===7){show('<div class="eyebrow">终章 · 灯塔的光</div><h1>我们一起回家</h1><p>潮王沉入宁静的海湾，黑潮终于退去。岚扶稳灯架，烁拉开遮光帘——第一束光越过海面，远处响起了船笛。</p><p>找回日志 '+Object.keys(game.relics).length+'/8 张。每一条路，都留下了你们互相等待与接应的脚印。</p><div class="row"><button id="again" class="primary">再一次双人冒险</button><button id="chapters">重玩与收集日志</button></div>','ending');$('again').onclick=()=>start(0,true);$('chapters').onclick=chapters;}else{show('<div class="eyebrow">两位冒险者已会合</div><h2>'+game.config.name+' · 完成</h2><p>下一段：'+stages[game.level+1].name+'<br>'+stages[game.level+1].subtitle+'</p><div class="row"><button id="next" class="primary">一起继续旅程</button><button id="repeat">重玩本区</button></div>','complete');$('next').onclick=()=>start(game.level+1);$('repeat').onclick=()=>start(game.level);}}};
document.addEventListener('keydown',e=>{if(e.code==='Backspace')e.preventDefault();if(rebind){e.preventDefault();if(e.code==='Escape'){rebind=null;settings();return;}if(['Tab','MetaLeft','MetaRight'].includes(e.code)||Object.values(game.bindings[0]).includes(e.code)||Object.values(game.bindings[1]).includes(e.code)){$('bindHelp').textContent='该按键已占用或属于系统键，请换一个。';return;}game.bindings[+rebind[0]][rebind[1]]=e.code;rebind=null;save();settings();return;}if(mode==='story'&&e.code==='KeyA'){e.preventDefault();play();return;}if(e.code==='Escape'){e.preventDefault();pause();return;}if(mode!=='play')return;const used=game.bindings.some(k=>Object.values(k).includes(e.code))||['NumpadEnter','ControlRight'].includes(e.code);if(used||e.ctrlKey)e.preventDefault();if(e.repeat&&['Enter','Backspace','NumpadEnter'].includes(e.code))return;if(!held[e.code])pressed[e.code]=true;held[e.code]=true;});document.addEventListener('keyup',e=>held[e.code]=false);window.addEventListener('blur',()=>{held={};pressed={};if(mode==='play')pause();});window.addEventListener('beforeunload',save);window.addEventListener('resize',()=>renderer.setSize(innerWidth,innerHeight));
function animate(dt){drawFloors();drawGates();actors.forEach((a,i)=>{const p=game.players[i];a.g.position.set(p.x,p.y,p.z);a.g.rotation.y=p.face;a.g.visible=!p.down||(Math.floor(time*7)%2===0);a.limbs[0].rotation.x=Math.sin(game.t*11)*p.moving*.6;a.limbs[1].rotation.x=-a.limbs[0].rotation.x;a.limbs[2].rotation.x=p.action>0?-1:a.limbs[1].rotation.x*.5;a.limbs[3].rotation.x=a.limbs[0].rotation.x*.5;a.tool.rotation.x=p.shield>0?-.5:0;a.aura.scale.setScalar(p.shield>0?2:1);});
for(const e of game.enemies){let m=enemyModels.get(e.id);if(!m){m=person(0,true);dynamic.add(m.g);enemyModels.set(e.id,m);addLabel(m.g,'守卫','enemy');}m.g.visible=e.hp>0;m.g.position.set(e.x,0,e.z);m.g.rotation.y=e.face;m.limbs[0].rotation.x=Math.sin(time*8)*.5;m.limbs[1].rotation.x=-m.limbs[0].rotation.x;m.aura.material=mat(e.armor?0xe9c674:e.alert?0xed8f7d:0x8cc4bc);}
for(const [id,m] of enemyModels)if(!game.enemies.some(e=>e.id===id))m.g.visible=false;
for(const o of game.config.objects){const m=objectModels.get(o.id);m.visible=game.objectActive(o)||o.type==='plate';if(['relic','shield','stormbow','chart'].includes(o.type))m.rotation.y=time*.6;if(o.type==='torch'){const n=o.id.slice(-1);m.children[2].scale.setScalar(game.flags['light'+n]>game.t?1.4:1);}if(o.type==='rune')m.rotation.y=Math.sin(time)*.2;}
beacons.forEach((b,i)=>{const o=game.objective(i);b.position.set(o.x,(o.y||0)+.1,o.z);b.children[1].rotation.y=time;b.visible=mode==='play';});
if(fogWall)fogWall.position.z=game.fog;if(bossModel){bossModel.visible=game.boss.hp>0;bossArms.forEach(a=>a.rotation.x=game.boss.state==='warn'?-1.8:game.boss.state==='open'?-.5:Math.sin(time)*.1);bossModel.userData.core.rotation.y=time;bossModel.userData.core.material=mat(game.boss.weak>0?0xffd38e:0x487f91);ringModel.visible=game.boss.ring>=0;ringModel.scale.setScalar(Math.max(.01,game.boss.ring));}
clear(fx);for(const s of game.shots){const m=box(fx,s.x,s.y,s.z,.06,.06,.65,0xe6d3a0);m.lookAt(s.tx,s.ty,s.tz);}for(const d of game.decoys){ball(fx,d.x,.2,d.z,.25,.22,.25,0xd0b574);ring(fx,d.x,.08,d.z,1+(time%1)*2,0xd5b77e,.035);}for(const e of game.effects)ring(fx,e.x,.05,e.z,2.2,0xe68f78,.1);
}
const temp=new THREE.Vector3(),look=new THREE.Vector3(),desired=new THREE.Vector3(),ray=new THREE.Raycaster();
function renderViews(dt){const online=typeof net!=="undefined"&&net.active,w=online?innerWidth:innerWidth/2,h=innerHeight;for(let i=0;i<2;i++){if(online&&i!==net.role){for(const l of labels)l.els[i].hidden=true;continue;}const offset=online?0:i*w;const p=game.players[i],cam=cameras[i];look.set(p.x-Math.sin(p.yaw)*1.8,(p.down?0:p.y)+1.3,p.z-Math.cos(p.yaw)*1.8);desired.set(p.x+Math.sin(p.yaw)*6.2,(p.down?0:p.y)+3.15,p.z+Math.cos(p.yaw)*6.2);const dir=desired.clone().sub(look),len=dir.length();ray.set(look,dir.normalize());const hit=ray.intersectObjects(occluders,false)[0];if(hit&&hit.distance<len)desired.copy(look).addScaledVector(dir,Math.max(1.3,hit.distance-.35));cam.position.lerp(desired,Math.min(1,dt*9));cam.fov=i===1&&p.mode===1?45:67;cam.aspect=w/h;cam.updateProjectionMatrix();cam.lookAt(look);cam.updateMatrixWorld();renderer.setViewport(offset,0,w,h);renderer.setScissor(offset,0,w,h);renderer.render(scene,cam);
for(const l of labels){const el=l.els[i];l.g.getWorldPosition(temp);const near=Math.hypot(temp.x-p.x,temp.z-p.z)<(i===1&&game.flags.scanUntil>game.t?50:19);temp.y+=l.kind==='player'?2.4:l.kind==='enemy'?2.6:2.2;temp.project(cam);el.hidden=mode!=='play'||!l.g.visible||!near||temp.z>1||Math.abs(temp.x)>.91||Math.abs(temp.y)>.84||(l.kind==='player'&&l.g===actors[i].g);if(!el.hidden){el.style.left=(offset+(temp.x*.5+.5)*w)+'px';el.style.top=((-temp.y*.5+.5)*h)+'px';if(l.kind==='enemy'){const e=game.enemies.find(e=>enemyModels.get(e.id)?.g===l.g);el.textContent=e?(e.armor?'重甲 · 先盾击':e.alert?'! 追击':'巡逻')+' '+'●'.repeat(Math.max(0,e.hp)):'';}}}}
}
function frame(now){const dt=Math.min(.065,(now-last)/1000);last=now;time+=dt;if(mode==='play'){acc+=dt;while(acc>=1/90){game.tick(1/90,held,pressed);pressed={};acc-=1/90;}uiTick+=dt;if(uiTick>.15){updateUI();uiTick=0;}}else acc=0;animate(dt);renderViews(dt);if(time>toastUntil)$('toast').hidden=true;requestAnimationFrame(frame);}
build();menu();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_tideborn_status',description:'Read the visible adventure status, player positions and independent third-person cameras without changing gameplay.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,region:game.config.name,status:game.status(),players:game.players.map(p=>({id:p.id+1,x:p.x,y:p.y,z:p.z,hp:p.hp,ability:p.mode,down:p.down})),cameras:cameras.map(c=>({x:c.position.x,y:c.position.y,z:c.position.z})),recoveries:game.recoveries})});}catch{}}


