'use strict';
const {Game,B,blocks,names,recipes,MIN,SIZE,YMIN,HEIGHT,hash}=Sandbox;
const $=id=>document.getElementById(id),canvas=$('view');
let stored=null;try{stored=JSON.parse(localStorage.getItem('prismMeadows.v1'));}catch(e){}
const game=new Game(stored),world=game.world;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0xaecbcd);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb9d6d5);scene.fog=new THREE.Fog(0xb9d6d5,26,76);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,110);camera.rotation.order='YXZ';
scene.add(new THREE.HemisphereLight(0xf2f7e3,0x647584,2.3));const sun=new THREE.DirectionalLight(0xffe5b3,2.5);sun.position.set(-30,60,15);scene.add(sun);
const terrainMat=new THREE.MeshLambertMaterial({vertexColors:true}),fluidMat=new THREE.MeshLambertMaterial({vertexColors:true,transparent:true,opacity:.7,depthWrite:false});
const tileCanvas=document.createElement('canvas');tileCanvas.width=16;tileCanvas.height=16;
if(tileCanvas.getContext){const tc=tileCanvas.getContext('2d');for(let x=0;x<16;x++)for(let y=0;y<16;y++){const v=Math.floor(220+hash(x,4,y)*35);tc.fillStyle='rgb('+v+','+v+','+v+')';tc.fillRect(x,y,1,1);}tc.fillStyle='rgba(40,60,45,.12)';tc.fillRect(0,0,16,1);tc.fillRect(0,0,1,16);const texture=new THREE.CanvasTexture(tileCanvas);texture.magFilter=THREE.NearestFilter;texture.minFilter=THREE.NearestFilter;texture.colorSpace=THREE.SRGBColorSpace;terrainMat.map=texture;}
const glassMat=new THREE.MeshLambertMaterial({vertexColors:true,transparent:true,opacity:.35,depthWrite:false});
const faceGeometry=new THREE.BoxGeometry(1,1,1).toNonIndexed(),facePos=faceGeometry.attributes.position.array,faceNorm=faceGeometry.attributes.normal.array,faceUV=faceGeometry.attributes.uv.array;
const chunks=new Map(),baseColors=blocks.map(b=>new THREE.Color(b[1]));
function rebuildChunk(cx,cz){if(cx<0||cz<0||cx>=8||cz>=8)return;const key=cx+','+cz,old=chunks.get(key);if(old){for(const m of old){scene.remove(m);m.geometry.dispose();}}
const buffers=[{p:[],n:[],c:[],uv:[]},{p:[],n:[],c:[],uv:[]},{p:[],n:[],c:[],uv:[]}];for(let x=MIN+cx*11;x<MIN+(cx+1)*11;x++)for(let z=MIN+cz*11;z<MIN+(cz+1)*11;z++)for(let y=YMIN;y<YMIN+HEIGHT;y++){
const id=world.get(x,y,z);if(!id)continue;const fluid=id===B.WATER||id===B.LAVA;const buf=buffers[id===B.GLASS?2:fluid?1:0];
for(let face=0;face<6;face++){const off=face*18,nx=faceNorm[off],ny=faceNorm[off+1],nz=faceNorm[off+2],neighbor=world.get(x+nx,y+ny,z+nz);if(neighbor!==0&&!(neighbor===B.WATER||neighbor===B.LAVA)&&neighbor!==B.GLASS)continue;if(neighbor===id)continue;if(fluid&&neighbor!==0)continue;
const color=(id===B.GRASS&&ny!==1)?new THREE.Color(0x8b7952):baseColors[id];const shade=.88+hash(x,y,z)*.18;
for(let v=0;v<6;v++){const i=off+v*3;buf.p.push(x+.5+facePos[i],y+.5+facePos[i+1],z+.5+facePos[i+2]);buf.n.push(nx,ny,nz);buf.uv.push(faceUV[(face*6+v)*2],faceUV[(face*6+v)*2+1]);let brightness=shade;if(id===B.DIVINE){const c=new THREE.Color().setHSL((face*.13+v*.11+hash(x,y,z))%1,.8,.67);buf.c.push(c.r,c.g,c.b);}else{if([6,7,8,9,10].includes(id))brightness*=v%3===0?.56:1.1;buf.c.push(color.r*brightness,color.g*brightness,color.b*brightness);}}
}}
const meshes=[];buffers.forEach((buf,i)=>{if(!buf.p.length)return;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(buf.p,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(buf.uv,2));geo.setAttribute('normal',new THREE.Float32BufferAttribute(buf.n,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(buf.c,3));geo.computeBoundingSphere();const mesh=new THREE.Mesh(geo,i===2?glassMat:i?fluidMat:terrainMat);scene.add(mesh);meshes.push(mesh);});chunks.set(key,meshes);}
for(let cx=0;cx<8;cx++)for(let cz=0;cz<8;cz++)rebuildChunk(cx,cz);
function updateChunks(){let n=0;for(const key of world.dirty){world.dirty.delete(key);const [x,z]=key.split(',').map(Number);rebuildChunk(x,z);if(++n>=4)break;}}
const materialCache={};function mat(color){return materialCache[color]||(materialCache[color]=new THREE.MeshLambertMaterial({color}));}
function box(parent,x,y,z,w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);parent.add(m);return m;}
function character(color=0x6baca0){const root=new THREE.Group();box(root,0,1.02,0,.54,.65,.32,color);box(root,0,1.57,0,.48,.46,.43,0xe9bd92);box(root,0,1.82,0,.52,.13,.46,0x514a49);box(root,0,1.62,.235,.51,.12,.05,0x514a49);box(root,-.12,1.59,-.223,.055,.065,.015,0x233b3d);box(root,.12,1.59,-.223,.055,.065,.015,0x233b3d);box(root,0,1.41,-.23,.18,.055,.025,0xd88e84);const leg1=box(root,-.16,.36,0,.22,.65,.25,0x384f61),leg2=box(root,.16,.36,0,.22,.65,.25,0x384f61),arm1=box(root,-.38,1,0,.2,.67,.22,color),arm2=box(root,.38,1,0,.2,.67,.22,color);box(root,-.16,.065,-.06,.24,.13,.35,0x293e48);box(root,.16,.065,-.06,.24,.13,.35,0x293e48);return{root,leg1,leg2,arm1,arm2};}
const avatar=character();scene.add(avatar.root);const leaf=box(avatar.root,.13,1.97,0,.3,.07,.16,0xb3d38c);leaf.rotation.z=.3;const armorMesh=box(avatar.root,0,1.05,0,.59,.63,.37,0xb9c7ce);armorMesh.visible=game.armorEquipped;
const held=new THREE.Group();avatar.root.add(held);held.position.set(.45,1,-.35);const firstHand=new THREE.Group();camera.add(firstHand);scene.add(camera);firstHand.position.set(.42,-.34,-.65);
let selected='hand',placeItem='dirt',third=false,heldKind='';
function refreshHeld(){held.clear();firstHand.clear();for(const g of [held,firstHand]){if(selected==='spear'){box(g,0,.15,0,.07,1.3,.07,0xa78957);const tip=box(g,0,.88,0,.16,.28,.12,0xccdbcd);tip.rotation.z=.25;}else if(selected==='hammer'){box(g,0,0,0,.1,.7,.1,0x946a47);box(g,0,.45,0,.55,.3,.32,0x9ca9ae);}else if(selected==='pick'){box(g,0,0,0,.08,.8,.08,0xa78150);box(g,0,.4,0,.52,.09,.12,[0,0xbf975a,0x99a6a7,0xd4d8cb][game.tools.pick]||0xbf975a);}else if(selected==='bucket'){box(g,0,0,0,.28,.3,.25,0xb0c6c5);if(game.bucket)box(g,0,.16,0,.24,.02,.21,game.bucket==='water'?0x66c8d4:0xffa255);}else if(selected==='block')box(g,0,0,0,.3,.3,.3,0xb69a70);else box(g,0,0,0,.17,.3,.18,0xe9bd92);}}
const props=[],actors=[],labels=[];
function label(mesh,text,friend=false){const el=document.createElement('div');el.className='worldLabel'+(friend?' friend':'');el.textContent=text;$('labels').appendChild(el);labels.push({mesh,el});}
function prop(type,x,y,z,name){const root=new THREE.Group();root.position.set(x,y,z);scene.add(root);if(type==='bench'){box(root,0,.68,0,1.65,.2,1,0xb5925b);for(const a of [-.65,.65])for(const b of [-.35,.35])box(root,a,.32,b,.12,.64,.12,0x654e3e);box(root,.3,.9,0,.45,.25,.4,0x758d92);box(root,-.45,.83,-.15,.3,.1,.6,0xdeb67b);}else if(type==='chest'){box(root,0,.4,0,1.1,.8,.65,0xac8054);box(root,0,.85,0,1.14,.12,.69,0x635b4e);box(root,0,.5,.36,.16,.22,.06,0xe6c36e);}else if(type==='toolbox'){box(root,0,.36,0,.85,.55,.5,0x739b9f);box(root,0,.67,0,.33,.13,.12,0xb1c9ba);}else if(type==='bed'){box(root,0,.35,0,1.15,.45,2,0x8c9e89);box(root,0,.61,-.65,1,.12,.6,0xf0e9cf);box(root,0,.6,.3,1,.08,1.1,0xca8e80);}props.push({type,x,y,z,root,name});label(root,name);return root;}
prop('bench',-5,4,-3,'工作台 · E 制作');prop('chest',5,4,-4,'空宝箱 · E 储物');prop('toolbox',-5,4,0,'工具箱 · E 配方指南');prop('bed',5,4,2,'你的床 · E 休息');
for(const f of game.furniture)prop(f.type,f.x,f.y,f.z,names[f.type]+' · E 使用');
function landmark(x,y,z,text,color){const g=new THREE.Group();g.position.set(x,y,z);box(g,0,1,0,.16,2,.16,0x817355);box(g,0,1.85,0,2,.65,.14,color);scene.add(g);label(g,text);return g;}
landmark(.5,3,12.5,'归家小径 · H 随时回家',0x9bb7a3);landmark(-18.5,4,-8,'星辉矿洞 · 阶梯向下',0xb9a6bc);landmark(23,1,11,'潮汐海岸 · 水中可游泳',0x78b6bd);landmark(-4,2,-23,'霜蓝冰湖 · 奔跑后滑行',0x9ccbd5);landmark(-29,3,22,'熔光泉 · 岩浆会灼伤',0xd6a17b);
function spawnNPC(name,x,z,color,visitor=false){const c=character(color);c.root.position.set(x,world.surface(x,z),z);scene.add(c.root);const a={...c,type:'npc',name,x,z,homeX:x,homeZ:z,phase:Math.random()*6,visitor,hp:100};actors.push(a);label(c.root,name+' · NPC',true);return a;}
spawnNPC('村民 阿禾',12,7,0xc3a370);spawnNPC('来访者 星野',-3,15,0x929ab5,true);spawnNPC('来访者 小栗',14,19,0xa5bb86,true);
function animal(type,x,z){const root=new THREE.Group();root.position.set(x,world.surface(x,z),z);scene.add(root);const c=type==='sheep'?0xe6e6d1:0xc78e76;box(root,0,.64,0,.83,.64,1.15,c);box(root,0,.8,-.7,.5,.46,.48,type==='sheep'?0x8a8980:0xdaab98);for(const a of [-.3,.3])for(const b of [-.38,.38])box(root,a,.23,b,.16,.45,.16,0x786959);box(root,-.13,.9,-.96,.06,.06,.025,0x293b3f);box(root,.13,.9,-.96,.06,.06,.025,0x293b3f);actors.push({root,type:'animal',name:type==='sheep'?'绵羊':'小猪',homeX:x,homeZ:z,phase:Math.random()*8});}
animal('sheep',10,21);animal('sheep',17,22);animal('pig',-12,18);
function swimmer(type,x,z){const root=new THREE.Group();root.position.set(x,.1,z);scene.add(root);const shark=type==='shark';box(root,0,0,0,shark?.8:.24,shark?.5:.22,shark?2:.65,shark?0x748d9d:0xf3b87e);box(root,0,.32,.15,shark?.12:.06,shark?.5:.15,shark?.5:.15,shark?0x587585:0xf0a86c);box(root,0,0,.99*(shark?1:.4),shark?.75:.3,.1,.12,0x7faeb4);box(root,0,.02,-(shark?1.02:.34),shark?.6:.18,.12,.04,0xe7eddf);actors.push({root,type,name:shark?'鲨鱼':'海鱼',homeX:x,homeZ:z,phase:Math.random()*7,hp:shark?18:3,cool:0});}
for(let i=0;i<8;i++)swimmer('fish',29+i%4*3,-8+Math.floor(i/4)*14);swimmer('shark',37,22);swimmer('shark',38,-24);
function slime(x,y,z){const root=new THREE.Group();root.position.set(x,y,z);box(root,0,.4,0,.85,.8,.85,0x867fab);box(root,-.2,.52,-.44,.14,.14,.03,0xeaf0d4);box(root,.2,.52,-.44,.14,.14,.03,0xeaf0d4);scene.add(root);actors.push({root,type:'slime',name:'洞穴晶怪',homeX:x,homeZ:z,hp:16,cool:0,phase:Math.random()*4});label(root,'洞穴晶怪');}
slime(-26,-9,-32);slime(-12,-9,-35);slime(-32,3,16);
let boat=null,riding=false;function makeBoat(x,z){if(boat)scene.remove(boat);boat=new THREE.Group();box(boat,0,0,0,1.6,.18,2.4,0xb28b58);box(boat,-.82,.32,0,.15,.6,2.5,0xccaa6d);box(boat,.82,.32,0,.15,.6,2.5,0xccaa6d);box(boat,0,.32,1.15,1.5,.6,.15,0xc19d61);box(boat,0,.32,-1.15,1.5,.6,.15,0xc19d61);box(boat,0,.3,0,1.5,.14,.35,0x8f7450);boat.position.set(x,1.05,z);scene.add(boat);label(boat,'你的船 · E 上下船');}
if(game.savedBoat&&Number.isFinite(game.savedBoat.x)&&Number.isFinite(game.savedBoat.z))makeBoat(game.savedBoat.x,game.savedBoat.z);
// A few drifting block clouds give the finite world an open sky.
const clouds=[];for(let i=0;i<9;i++){const g=new THREE.Group();for(let j=0;j<4;j++)box(g,j*3,0,Math.sin(j)*2,6,1.5,4,0xe7eee3);g.position.set(-40+i*11,17+(i%3)*2,-36+(i*17)%75);scene.add(g);clouds.push(g);}
const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.015,1.015,1.015)),new THREE.LineBasicMaterial({color:0xfff0b1}));scene.add(outline);outline.visible=false;
const placePreview=new THREE.Mesh(new THREE.BoxGeometry(.98,.98,.98),new THREE.MeshBasicMaterial({color:0x85f5bb,transparent:true,opacity:.32,depthWrite:false}));scene.add(placePreview);placePreview.visible=false;
let expectedPointerUnlock=false,secondaryPress=false,secondaryUsed=false,lastLookX=null,lastLookY=null,lookSource='canvas';
let panelOpen=true,started=false,keys={},yaw=Math.PI,pitch=-.05,velocity=new THREE.Vector3(),ground=false,crouching=false,attackDown=false,attackCool=0,skillCool=0,invulnerable=0,slam=false,fallStart=game.pos.y,mining={key:'',progress:0},time=0,messageUntil=0,currentTarget=null,waypoint='wood',saveClock=0,mouseDragging=false,mouseMoved=0,pausedByBlur=false;
const waypoints={home:{x:.5,y:4,z:5.5,name:'大房子'},wood:{x:5,y:3,z:15,name:'门前树木'},mine:{x:-18.5,y:4,z:-8,name:'星辉矿洞入口'},divine:{x:-15.5,y:-7,z:-37.5,name:'矿洞深处神石'},sea:{x:27,y:1,z:11,name:'潮汐海岸'},ice:{x:0,y:2,z:-28,name:'霜蓝冰湖'},lava:{x:-32,y:3,z:22,name:'熔光泉'}};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;messageUntil=time+4.5;}
function save(){try{localStorage.setItem('prismMeadows.v1',JSON.stringify(game.save(boat?{x:boat.position.x,z:boat.position.z}:null)));$('savelabel').textContent='已保存 · 本地世界 · 来访者均为 NPC';return true;}catch(e){$('savelabel').textContent='浏览器无法保存 · 请导出存档';return false;}}
function toolName(){return selected==='pick'?['未制作镐','木镐','石镐','铁镐'][game.tools.pick]:({hand:'空手',spear:'长矛',hammer:'重锤',block:'方块',bucket:'桶'})[selected];}
function toolbar(){const kinds=['hand','pick','spear','hammer','block','bucket'];$('toolbar').innerHTML=kinds.map((k,i)=>{const unlocked=['hand','block'].includes(k)||(k==='pick'?game.tools.pick>0:game.tools[k]);let subtitle=k==='block'?(names[placeItem]+' ×'+(game.inv[placeItem]||0)):k==='bucket'?(game.bucket==='water'?'水':game.bucket==='lava'?'岩浆':'空桶'):k==='spear'?'Q 腾空':k==='hammer'?'Q 下砸':k==='pick'?['需先制作','采石头','采铁/金/宝石','采钻石/神石'][game.tools.pick]:'采木头 / 泥土';return `<button class="slot ${k===selected?'active':''} ${unlocked?'':'locked'}" data-tool="${k}"><span class="key">${i+1}</span><strong>${k==='pick'?['镐子','木镐','石镐','铁镐'][game.tools.pick]:{hand:'空手',spear:'长矛',hammer:'重锤',block:'方块',bucket:'桶'}[k]}</strong><small>${unlocked?subtitle:'未制作'}</small></button>`;}).join('');document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));refreshHeld();}
function selectTool(k){if(!['hand','block'].includes(k)&&!(k==='pick'?game.tools.pick:game.tools[k])){toast('还没有这件工具，按 C 查看配方');return;}selected=k;if(k==='block'&&!(game.inv[placeItem]>0)){const available=Object.keys(names).find(id=>game.inv[id]>0);if(available)placeItem=available;}mining={key:'',progress:0};toolbar();}
function showPanel(html){panelOpen=true;attackDown=false;keys={};if(document.pointerLockElement){expectedPointerUnlock=true;document.exitPointerLock();}$('panel').hidden=false;$('panel').innerHTML='<div class="sheet">'+html+'</div>';}
function resume(lock=true){panelOpen=false;started=true;keys={};attackDown=false;$('panel').hidden=true;if(lock&&canvas.requestPointerLock){try{const p=canvas.requestPointerLock();if(p?.catch)p.catch(()=>toast(selected==='block'?'已选择'+names[placeItem]+'：F 放置；J/L、I/K 或右下视角区瞄准绿色落点':'转身：J/L，抬低：I/K，或拖动右下视角区；F 放置'));}catch(e){}}}
function help(title='这片原野，属于你'){showPanel(`<div class="eyebrow">PRISM MEADOWS · 离线方块沙盒</div><h1>${title}</h1><p>你拥有一座大房子，背包从空开始。走出南门采木，制作镐子，再向矿洞深处寻找彩虹色的<b>神石</b>。这里没有关卡，也没有自动代劳的剧情。</p><div class="grid"><div class="tile"><h3>走动与视角</h3><p>方向键 ↑↓←→ 移动<br>鼠标看四周 / 准星瞄准<br>J / L 左右转身，I / K 抬低视角<br>也可拖动右下角视角区<br>空格跳跃或向上游<br>Shift 蹲下 / 潜水<br>V 第一 / 第三人称</p></div><div class="tile"><h3>动手创造</h3><p>A 或左键：持续采集 / 攻击<br>F 或轻点右键：放方块 / 倒桶 / 用物品<br>1—6 明确切换工具，不自动换<br>C 配方 · B 背包选方块<br>E 工作台 / 宝箱 / NPC / 船</p></div><div class="tile"><h3>探索与保命</h3><p>H 随时回家 · M 地标导航<br>长矛 Q 腾空，重锤 Q 空中下砸<br>Esc 暂停 · 右上角⛶全屏<br>死亡保留背包，在家复活<br>无鼠标锁定也可玩：拖动右下角视角区，或 J/L、I/K</p></div></div><p class="mini">开局路线：出门按住 A 采 3 木 → C 徒手做木镐 → 2 装备镐 → 去矿洞挖石头 → H 归家，在工作台旁按 C 做石镐。长矛配方：4 木 + 2 石；矿洞深处的神石需要铁镐。来访角色均为电脑 NPC。</p><div class="row"><button class="primary" id="play">${started?'继续探索':'进入我的世界 →'}</button><button id="panelFullscreen">⛶ 全屏</button><button id="openCraft">查看配方</button><button id="openMap">地标导航</button><button id="export">导出存档</button><button id="import">导入存档</button></div><p class="mini">自动本地保存。世界大小 88×88，地下可挖至基岩。浏览器禁用存储时可导出 JSON 存档。建议电脑全屏游玩。</p>`);$('play').onclick=()=>resume();$('panelFullscreen').onclick=()=>$('fullscreen').click();$('openCraft').onclick=craftPanel;$('openMap').onclick=mapPanel;$('export').onclick=exportSave;$('import').onclick=importSave;}
function nearBench(){return props.some(p=>p.type==='bench'&&Math.hypot(game.pos.x-p.x,game.pos.y-p.y,game.pos.z-p.z)<4.3);}
function craftPanel(){showPanel(`<h2>制作 · 亲手开启旅程</h2><p>${nearBench()?'你正在工作台旁，可以制作所有配方。':'木镐、木板、工作台可徒手制作；其余配方请到工作台旁（H 归家，向左后方走）。'}</p><div class="grid">${Object.entries(recipes).map(([id,r])=>`<div class="tile"><h3>${r.name}${r.hand?' · 徒手':''}</h3><p>${Object.entries(r.cost).map(([k,n])=>`${names[k]} ${game.inv[k]||0}/${n}`).join('　')}</p><p>${{woodpick:'可采石头；制作后按 2 装备',stonepick:'可采铁、金、红石、绿宝石',ironpick:'可采钻石与彩虹神石',spear:'按 3 装备，Q 腾空（冷却 5 秒）',hammer:'按 4 装备，在空中 Q 强力下砸',bucket:'按 6 装备，左键装液体，右键倒出',boat:'制作后到水边按 E 放船并登船',armor:'制作后在 B 背包中手动装备，减少 40% 伤害（取整，至少受 1 点）',plank:'用木头加工，作为建筑方块放置',brick:'由石头加工，用于墙壁和屋顶',glass:'沙子与石头加工的透亮色玻璃方块',bench:'放置后可在附近制作所有高级配方',chest:'放置后 E 存取材料，所有宝箱共享仓库',toolbox:'放置后 E 打开操作与配方指南',bed:'放置后 E 休息并恢复生命'}[id]}</p><button data-craft="${id}">制作${r.name}</button></div>`).join('')}</div><div class="row"><button class="primary" id="back">返回世界</button><button id="homeCraft">回家到工作台附近</button></div>`);document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>{const r=game.craft(b.dataset.craft,nearBench());if(r.ok){GameAudio.sfx('craft');save();toolbar();craftPanel();toast('制作完成：'+r.name+'。请用数字键手动装备');}else toast(r.reason);});$('back').onclick=()=>resume();$('homeCraft').onclick=()=>{goHome(true);craftPanel();};}
function inventoryPanel(chest=false){showPanel(`<h2>${chest?'家中宝箱（共享仓库）':'背包与建筑材料'}</h2><p>铁甲：${game.armorEquipped?'已装备 · 减伤 40%':game.tools.armor?'已制作，尚未装备':'尚未制作'}</p>${game.tools.armor?'<button id=armorToggle>装备 / 卸下铁甲</button>':''}<p>工具保留在工具栏。点击一种材料，设为 5 号栏的放置方块；选择有数量的材料后自动返回游戏。让中心准星对准近处地面，看到绿色落点后按 F 放置；也可轻点右键。</p><div class="grid">${Object.entries(names).map(([k,n])=>`<button class="tile" data-block="${k}" ${(game.inv[k]||0)<1?'disabled':''}><h3>${n} × ${game.inv[k]||0}</h3>${chest?'<span class="mini">宝箱内 '+(game.chest[k]||0)+'</span>':'<span class="mini">点击选择建筑材料</span>'}</button>`).join('')}</div><div class="row">${chest?'<button id="store">存入全部材料</button><button id="take">取出全部材料</button>':''}<button class="primary" id="back">返回世界</button></div>`);document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>{if(!(game.inv[b.dataset.block]>0)){toast('这种材料数量为 0，请选择有材料的一项');return;}placeItem=b.dataset.block;selectTool('block');resume();toast('已选择'+names[placeItem]+' ×'+game.inv[placeItem]+'：看到绿色落点后按 F 放置');});$('back').onclick=()=>resume();if(game.tools.armor)$('armorToggle').onclick=()=>{game.equipArmor();save();inventoryPanel(chest);toast(game.armorEquipped?'已装备铁甲，受到的伤害减少':'已卸下铁甲');};if(chest){$('store').onclick=()=>{game.storeAll();save();toolbar();inventoryPanel(true);};$('take').onclick=()=>{game.takeAll();save();toolbar();inventoryPanel(true);};}}
function mapPanel(){showPanel(`<h2>原野地标 · 选择导航目标</h2><p>选择后，左上角会持续显示方向与距离。朝指示方向转动视角，再向前走。H 可随时归家。</p><div class="grid">${Object.entries(waypoints).map(([k,p])=>`<button class="tile" data-way="${k}"><h3>${p.name}</h3><span class="mini">坐标 ${p.x.toFixed(0)}, ${p.z.toFixed(0)}${k==='divine'?' · 深度 −7 · 铁镐':''}</span></button>`).join('')}</div><p>矿洞入口在房子的西北方，沿敞开的阶梯向下。最深处后墙依次可见铁、黄金、绿宝石、红石、钻石和神石。海岸在东方，冰湖在北方，岩浆泉在西南方。</p><div class="row"><button class="primary" id="back">返回世界</button></div>`);document.querySelectorAll('[data-way]').forEach(b=>b.onclick=()=>{waypoint=b.dataset.way;resume();toast('导航目标：'+waypoints[waypoint].name);});$('back').onclick=()=>resume();}
function exportSave(){save();const blob=new Blob([JSON.stringify(game.save(boat?{x:boat.position.x,z:boat.position.z}:null))],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='神石原野存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已导出存档');}
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(data.version!==1||!data.edits||!data.tools)throw Error();localStorage.setItem('prismMeadows.v1',JSON.stringify(data));location.reload();}catch(e){toast('存档格式不正确，未修改当前世界');}};input.click();}
function goHome(bench=false){riding=false;game.pos={x:bench?-4:.5,y:4,z:bench?-1:5.5};velocity.set(0,0,0);yaw=bench?0:Math.PI;pitch=-.05;slam=false;invulnerable=2;save();toast('已回到自己的大房子');}
function damage(n,why){if(invulnerable>0)return;GameAudio.sfx('hurt');n=game.absorbDamage(n);game.hp=Math.max(0,game.hp-n);invulnerable=1.3;toast(why+' −'+n+' 生命');if(game.hp<=0){goHome();game.hp=10;toast('已在家复活，背包和已建造方块均保留');}hud();}
function interact(){if(riding){riding=false;game.pos.x+=1.5;game.pos.y=1.2;toast('已下船，空格向上游，Shift 潜水');return;}
if(boat&&Math.hypot(game.pos.x-boat.position.x,game.pos.z-boat.position.z)<3.2){riding=true;game.pos.y=1.45;third=true;toast('已上船：方向键划船，E 下船');return;}
for(const p of props)if(Math.hypot(game.pos.x-p.x,game.pos.y-p.y,game.pos.z-p.z)<2.8){if(p.type==='bench')craftPanel();else if(p.type==='chest')inventoryPanel(true);else if(p.type==='bed'){game.hp=10;save();toast('休息后生命已恢复');hud();}else help('工具箱 · 从零开始');return;}
const npc=actors.find(a=>a.type==='npc'&&a.root.position.distanceTo(new THREE.Vector3(game.pos.x,game.pos.y,game.pos.z))<3.5);if(npc){toast(npc.name+'（NPC）：'+(npc.visitor?'我来参观你的家！神石藏在西北矿洞的最深处。':'长矛用 4 木和 2 石制作。先木镐采石，再石镐采铁，最后做铁镐！'));return;}
if(game.tools.boat){let x=game.pos.x-Math.sin(yaw)*2,z=game.pos.z-Math.cos(yaw)*2;if(world.get(x,0,z)===B.WATER){makeBoat(x,z);riding=true;third=true;game.pos.y=1.45;toast('放下船并登船：方向键划船，E 下船');save();return;}}
toast('靠近工作台、宝箱、床、NPC 或船再按 E；制作船后可在水边放船');}
function skill(){if(skillCool>0&&!(selected==='hammer'&&!ground)){toast('技能冷却 '+Math.ceil(skillCool)+' 秒');return;}if(riding){toast('先按 E 下船再使用技能');return;}if(selected==='spear'&&game.tools.spear){GameAudio.sfx('jump');velocity.y=12;ground=false;skillCool=5;fallStart=game.pos.y;burst(game.pos.x,game.pos.y,game.pos.z,0xe4ecc1,18);toast('长矛腾空！可在空中按 4 切重锤，再 Q 下砸');}else if(selected==='hammer'&&game.tools.hammer){if(ground){toast('重锤下砸需要先跳起或从高处落下');return;}slam=true;velocity.y=-24;skillCool=0;toast('重锤下砸！');}else toast('长矛和重锤可使用 Q 技能');}
function collide(x,y,z,height){if(x<MIN+.35||x>MIN+SIZE-.35||z<MIN+.35||z>MIN+SIZE-.35)return true;for(let xx=Math.floor(x-.28);xx<=Math.floor(x+.28);xx++)for(let zz=Math.floor(z-.28);zz<=Math.floor(z+.28);zz++)for(let yy=Math.floor(y+.03);yy<=Math.floor(y+height-.03);yy++)if(world.solid(xx,yy,zz))return true;return false;}
function liquidAt(){const b=world.get(game.pos.x,game.pos.y+.45,game.pos.z);return b===B.WATER?'water':b===B.LAVA?'lava':null;}
function movement(dt){const p=game.pos;const wantsCrouch=!!keys.Shift; if(wantsCrouch)crouching=true;else if(!collide(p.x,p.y,p.z,1.72))crouching=false;const height=crouching?1.05:1.72;
const forward=(keys.ArrowUp?1:0)-(keys.ArrowDown?1:0),side=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);let ix=-Math.sin(yaw)*forward+Math.cos(yaw)*side,iz=-Math.cos(yaw)*forward-Math.sin(yaw)*side;const len=Math.hypot(ix,iz);if(len>1){ix/=len;iz/=len;}
if(riding&&boat){const nx=boat.position.x+ix*6*dt,nz=boat.position.z+iz*6*dt;if(world.get(nx,0,nz)===B.WATER){boat.position.x=nx;boat.position.z=nz;}boat.rotation.y=yaw;boat.position.y=1.03+Math.sin(time*3)*.045;p.x=boat.position.x;p.z=boat.position.z;p.y=1.45;velocity.set(0,0,0);return;}
const liquid=liquidAt(),ice=world.get(p.x,p.y-.1,p.z)===B.ICE,speed=crouching?1.7:liquid?2.8:4.8,lerp=ice?1.1:13;velocity.x+=(ix*speed-velocity.x)*Math.min(1,lerp*dt);velocity.z+=(iz*speed-velocity.z)*Math.min(1,lerp*dt);
if(liquid==='water'){velocity.y+=(keys[' ']?12:keys.Shift?-9:4)*dt;velocity.y-=3*dt;velocity.y*=1-dt*2;velocity.y=Math.max(-3,Math.min(4,velocity.y));if(ground&&keys[' '])velocity.y=6;}
else{velocity.y-=22*dt;if(keys[' ']&&ground){GameAudio.sfx('jump');velocity.y=8.4;ground=false;}}
if(liquid==='lava')damage(2,'岩浆灼伤');
for(const axis of ['x','z']){const delta=velocity[axis]*dt;if(!delta)continue;const next={...p,[axis]:p[axis]+delta};if(!collide(next.x,next.y,next.z,height)){
if(!(crouching&&ground&&!liquid&&!collide(next.x,next.y-.15,next.z,height)))p[axis]+=delta;
}else velocity[axis]=0;}
const dy=velocity.y*dt,steps=Math.max(1,Math.ceil(Math.abs(dy)/.2));let landed=false;for(let i=0;i<steps;i++){if(!collide(p.x,p.y+dy/steps,p.z,height)){p.y+=dy/steps;ground=false;}else{if(velocity.y<0){landed=!ground;ground=true;}velocity.y=0;break;}}
if(velocity.y<=0&&collide(p.x,p.y-.055,p.z,height))ground=true;
if(velocity.y>0)fallStart=Math.max(fallStart,p.y);if(landed){const drop=fallStart-p.y;if(slam){slam=false;skillCool=2;shockwave(p.x,p.y,p.z);for(const a of actors)if(['slime','shark'].includes(a.type)&&a.hp>0&&Math.hypot(a.root.position.x-p.x,a.root.position.z-p.z)<5.5&&Math.abs(a.root.position.y-p.y)<4)hurtActor(a,18+Math.min(16,drop*2));toast('轰！重锤震波击中周围敌人');}else if(drop>6&&liquid!=='water')damage(Math.min(7,Math.floor(drop-5)),'高处跌落');fallStart=p.y;}if(ground)fallStart=p.y;
if(p.y<YMIN-3){goHome();damage(2,'跌出地底');}
}
const effects=[];function burst(x,y,z,color,count=12){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.11,.11,.11),mat(color));m.position.set(x,y+.8,z);scene.add(m);effects.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*4,(Math.random()-.5)*4),life:.6});}}
function shockwave(x,y,z){GameAudio.sfx('explode');const ring=new THREE.Mesh(new THREE.RingGeometry(.5,.75,32),new THREE.MeshBasicMaterial({color:0xffe2a0,transparent:true,opacity:.85,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,y+.08,z);scene.add(ring);effects.push({mesh:ring,life:.65,ring:true});burst(x,y,z,0xe9d9a8,30);}
function hurtActor(a,n){if(a.hp<=0)return;GameAudio.sfx('hit');a.hp-=n;burst(a.root.position.x,a.root.position.y,a.root.position.z,0xe5cbad,9);if(a.hp<=0){scene.remove(a.root);if(a.type==='slime')game.add('stone',2);toast(a.name+'已被击败'+(a.type==='slime'?' · 获得 2 石头':''));toolbar();}}
function castVoxel(origin,direction,max=6){
let x=Math.floor(origin.x),y=Math.floor(origin.y),z=Math.floor(origin.z),distance=0,normal=null;
const step={x:Math.sign(direction.x),y:Math.sign(direction.y),z:Math.sign(direction.z)},delta={},next={};
for(const axis of ['x','y','z']){delta[axis]=direction[axis]===0?Infinity:Math.abs(1/direction[axis]);const cell=Math.floor(origin[axis]);next[axis]=direction[axis]===0?Infinity:((step[axis]>0?cell+1:cell)-origin[axis])/direction[axis];}
for(let count=0;count<256&&distance<=max;count++){const id=world.get(x,y,z);if(id!==0)return{x,y,z,id,distance,normal,previous:normal?{x:x+normal.x,y:y+normal.y,z:z+normal.z}:null,point:{x:origin.x+direction.x*distance,y:origin.y+direction.y*distance,z:origin.z+direction.z*distance}};let axis=next.x<=next.y&&next.x<=next.z?'x':next.y<=next.z?'y':'z';distance=next[axis];if(!Number.isFinite(distance))break;next[axis]+=delta[axis];normal={x:0,y:0,z:0};normal[axis]=-step[axis];if(axis==='x')x+=step.x;else if(axis==='y')y+=step.y;else z+=step.z;}return null;}
function placementInfo(){if(!['block','bucket'].includes(selected))return{ok:false,reason:'按 5 选择方块，B 选择已有材料'};
if(selected==='block'&&!(game.inv[placeItem]>0))return{ok:false,reason:names[placeItem]+'数量为 0，按 B 选择已有材料'};
if(selected==='bucket'&&!game.bucket)return{ok:false,reason:'空桶：左键装水或岩浆，再按 F 倒出'};
if(!currentTarget||currentTarget.actor)return{ok:false,reason:'请把中心 + 对准 5 格内的地面或墙面；J/L 转身，I/K 抬低视角'};
const p=currentTarget.previous;if(!p)return{ok:false,reason:'视角贴在方块内部，请退后一点再瞄准'};
if(world.index(p.x,p.y,p.z)<0)return{ok:false,p,reason:'已到世界边界，无法放置'};
if(world.get(p.x,p.y,p.z)!==0)return{ok:false,p,reason:'落点已被占用，请对准另一面'};
const player=game.pos;if(p.x+1>player.x-.28&&p.x<player.x+.28&&p.z+1>player.z-.28&&p.z<player.z+.28&&p.y<player.y+(crouching?1.05:1.72)&&p.y+1>player.y+.03)return{ok:false,p,reason:'落点在自己身上，请对准前方一格地面'};
if(selected==='block'&&['bench','chest','toolbox','bed'].includes(placeItem)&&props.some(f=>Math.hypot(f.x-p.x-.5,f.z-p.z-.5)<1.5&&Math.abs(f.y-p.y)<2))return{ok:false,p,reason:'家具之间需要留出空间'};
return{ok:true,p,reason:'F / 轻点右键：放置'+(selected==='bucket'?(game.bucket==='water'?'水':'岩浆'):names[placeItem])};}

function aim(){const dir=new THREE.Vector3();camera.getWorldDirection(dir);let target=castVoxel(camera.position,dir,third?10.2:5.5);if(target&&Math.hypot(target.point.x-game.pos.x,target.point.y-game.pos.y-(crouching?.87:1.55),target.point.z-game.pos.z)>5.5)target=null;let actorTarget=null;for(const a of actors){if(a.hp<=0)continue;const center=a.root.position.clone().add(new THREE.Vector3(0,a.type==='npc'?1:.4,0)),delta=center.clone().sub(camera.position),d=delta.dot(dir);if(d>0&&d<5&&(target?d<target.distance:true)&&delta.lengthSq()-d*d<.65){actorTarget=a;break;}}
if(['block','bucket'].includes(selected))actorTarget=null;currentTarget=actorTarget?{actor:actorTarget}:target;outline.visible=!!target&&!actorTarget;if(outline.visible)outline.position.set(target.x+.5,target.y+.5,target.z+.5);
placePreview.visible=false;if(['block','bucket'].includes(selected)){const info=placementInfo();if(info.p){placePreview.visible=true;placePreview.position.set(info.p.x+.5,info.p.y+.5,info.p.z+.5);placePreview.material.color.setHex(info.ok?0x85f5bb:0xff827a);}$('targetText').textContent=info.reason;return;}
if(actorTarget)$('targetText').textContent=actorTarget.name+(actorTarget.type==='npc'?' · E 交流':' · A 攻击');else if(target){const info=game.mineInfo(target.id,selected);$('targetText').textContent=blocks[target.id][0]+' · '+(selected==='bucket'?'左键盛装 / 右键倒出':info.ok?'按住 A / 左键采集':info.reason);}else $('targetText').textContent='触及范围 5 格 · 对准方块';}
function useAttack(dt){if(!attackDown){mining={key:'',progress:0};$('minebar').style.width='0';return;}if(!currentTarget)return;
if(currentTarget.actor){if(attackCool>0)return;attackCool=.5;const a=currentTarget.actor;if(['npc','animal','fish'].includes(a.type)){toast(a.type==='npc'?'友好的 NPC：靠近按 E 交流':'这位原野伙伴不会攻击你');return;}const range=selected==='spear'?4.5:3;if(a.root.position.distanceTo(new THREE.Vector3(game.pos.x,game.pos.y,game.pos.z))>range){toast('再靠近一点才能击中');return;}hurtActor(a,selected==='spear'?6:selected==='hammer'?8:1);return;}
const hit=currentTarget;if(selected==='bucket'){if(attackCool>0)return;attackCool=.4;const r=game.scoop(hit.x,hit.y,hit.z);toast(r.ok?'已装入'+(game.bucket==='water'?'水':'岩浆')+'，右键倒出':r.reason);toolbar();return;}
const info=game.mineInfo(hit.id,selected);if(!info.ok){if(attackCool<=0){toast(info.reason);attackCool=1.1;}return;}const key=hit.x+','+hit.y+','+hit.z;if(mining.key!==key)mining={key,progress:0};mining.progress+=dt;const fraction=Math.min(1,mining.progress/info.time);$('minebar').style.width=(fraction*100)+'%';outline.material.color.setHex(fraction>.5?0xffffff:0xffedaa);if(fraction>=1){const r=game.mine(hit.x,hit.y,hit.z,selected);if(r.ok){GameAudio.sfx(r.divine?'victory':'mine');burst(hit.x+.5,hit.y,hit.z+.5,blocks[hit.id][1],8);if(r.divine){toast('找到神石！彩虹之力已收入背包，世界仍可自由探索');waypoint='home';save();}else toast('采集 '+names[r.item]+' +1');toolbar();}mining={key:'',progress:0};}}
function useSecondary(){if(panelOpen)return;if(selected==='spear'||selected==='hammer'){skill();return;}updateCamera(0);aim();const info=placementInfo();if(!info.ok){toast(info.reason);return;}const p=info.p;let r;const placedName=selected==='bucket'?(game.bucket==='water'?'水':'岩浆'):names[placeItem];if(selected==='bucket')r=game.pour(p.x,p.y,p.z);else if(['bench','chest','toolbox','bed'].includes(placeItem)){r=game.placeFurniture(placeItem,p.x+.5,p.y,p.z+.5);if(r.ok)prop(placeItem,p.x+.5,p.y,p.z+.5,names[placeItem]+' · E 使用');}else r=game.place(p.x,p.y,p.z,placeItem);toast(r.ok?'已放置'+placedName+' · 剩余 '+(selected==='bucket'?0:game.inv[placeItem]):r.reason);toolbar();if(r.ok){GameAudio.sfx('place');save();updateChunks();aim();}}

function updateActors(dt){for(const a of actors){if(a.hp<=0)continue;a.cool=Math.max(0,(a.cool||0)-dt);if(a.type==='fish'||a.type==='shark'){const chase=a.type==='shark'&&liquidAt()==='water'&&!riding&&Math.hypot(a.root.position.x-game.pos.x,a.root.position.z-game.pos.z)<9;const tx=chase?game.pos.x:a.homeX+Math.sin(time*.25+a.phase)*3,tz=chase?game.pos.z:a.homeZ+Math.cos(time*.21+a.phase)*4;const dx=tx-a.root.position.x,dz=tz-a.root.position.z;const d=Math.hypot(dx,dz)||1,speed=a.type==='shark'?1.8:1.1;let nx=a.root.position.x+dx/d*dt*speed,nz=a.root.position.z+dz/d*dt*speed;if(world.get(nx,0,nz)===B.WATER){a.root.position.x=nx;a.root.position.z=nz;}a.root.position.y=.15+Math.sin(time*2+a.phase)*.15;a.root.rotation.y=Math.atan2(-dx,-dz);if(chase&&d<1.5&&a.cool<=0){damage(2,'鲨鱼咬伤');a.cool=1.5;}continue;}
let tx=a.homeX+Math.sin(time*.18+a.phase)*2,tz=a.homeZ+Math.cos(time*.15+a.phase)*2;if(a.type==='slime'&&Math.abs(game.pos.y-a.root.position.y)<3&&Math.hypot(game.pos.x-a.root.position.x,game.pos.z-a.root.position.z)<8){tx=game.pos.x;tz=game.pos.z;}const dx=tx-a.root.position.x,dz=tz-a.root.position.z,d=Math.hypot(dx,dz)||1,speed=a.type==='slime'?1.3:.65;const nx=a.root.position.x+dx/d*dt*speed,nz=a.root.position.z+dz/d*dt*speed;let foot=a.root.position.y;const testHeight=a.type==='npc'?1.8:.9;if(!collide(nx,foot,nz,testHeight)&&world.solid(nx,foot-.15,nz)){a.root.position.x=nx;a.root.position.z=nz;}a.root.rotation.y=Math.atan2(-dx,-dz);
if(a.leg1){a.leg1.rotation.x=Math.sin(time*5+a.phase)*.25;a.leg2.rotation.x=-a.leg1.rotation.x;a.arm1.rotation.x=-a.leg1.rotation.x;a.arm2.rotation.x=a.leg1.rotation.x;}
if(a.type==='slime'){a.root.scale.y=1+Math.sin(time*6+a.phase)*.09;if(Math.hypot(a.root.position.x-game.pos.x,a.root.position.z-game.pos.z)<1.15&&Math.abs(game.pos.y-foot)<2&&a.cool<=0){damage(1,'晶怪碰撞');a.cool=1;}}
}}
function hud(){const p=game.pos,w=waypoints[waypoint],dx=w.x-p.x,dz=w.z-p.z;const distance=Math.hypot(dx,dz),desired=Math.atan2(-dx,-dz),relative=Math.atan2(Math.sin(desired-yaw),Math.cos(desired-yaw));const direction=Math.abs(relative)<.35?'↑ 前方':Math.abs(relative)>2.5?'↓ 身后':relative>0?'← 左转':'→ 右转';$('hearts').textContent='♥'.repeat(game.hp)+'♡'.repeat(10-game.hp);$('status').textContent=`${riding?'划船':liquidAt()==='water'?'游泳':crouching?'蹲下':ground?'行走':'腾空'} · ${Math.round(p.x)}, ${Math.round(p.y)}, ${Math.round(p.z)} · ${game.found?'已发现神石':'神石未发现'}${game.armorEquipped?' · 铁甲':''}`;
let task=!game.tools.pick?'出南门采 3 木 → C 制作木镐':game.tools.pick===1?'去矿洞采石 → 工作台做石镐':game.tools.pick===2?'石镐采 3 铁 + 2 木 → 工作台做铁镐':!game.found?'铁镐已就绪！前往矿洞后墙寻找神石':'神石已找到！继续建造你的世界';$('guide').innerHTML=`<b>${task}</b><br>${w.name}　${direction} ${Math.round(distance)} 米<br><span class="mini">M 更换导航 · H 随时回家<br>当前：${toolName()}${skillCool>0?' · 技能 '+Math.ceil(skillCool)+' 秒':''}</span>`;}
function updateCamera(dt){const p=game.pos,eye=p.y+(crouching?.87:1.55);armorMesh.visible=game.armorEquipped;avatar.root.position.set(p.x,p.y,p.z);avatar.root.rotation.y=yaw;avatar.root.scale.y=crouching?.62:1;avatar.root.visible=third;avatar.leg1.rotation.x=Math.sin(time*10)*Math.min(.6,Math.hypot(velocity.x,velocity.z)*.12);avatar.leg2.rotation.x=-avatar.leg1.rotation.x;held.rotation.x=attackDown?Math.sin(time*16)*.4:0;firstHand.visible=!third;firstHand.rotation.x=attackDown?Math.sin(time*16)*.4:0;camera.rotation.set(pitch,yaw,0,'YXZ');camera.position.set(p.x,eye,p.z);
if(third){const direction=new THREE.Vector3();camera.getWorldDirection(direction);const backward=direction.clone().negate(),hit=castVoxel(camera.position,backward,4.5);const d=hit?Math.max(.1,hit.distance-.18):4.5;camera.position.addScaledVector(backward,d);}
}
function updateLabels(){$('lookPad').hidden=panelOpen||document.pointerLockElement===canvas;const pv=new THREE.Vector3();for(const item of labels){if(!item.mesh.parent){item.el.hidden=true;continue;}item.mesh.getWorldPosition(pv);pv.y+=2.15;const dist=pv.distanceTo(camera.position);pv.project(camera);item.el.hidden=dist>16||pv.z>1||pv.z<0||panelOpen;if(!item.el.hidden){item.el.style.left=(pv.x*.5+.5)*innerWidth+'px';item.el.style.top=(-pv.y*.5+.5)*innerHeight+'px';}}}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Shift','a','A','c','C','b','B','m','M','e','E','q','Q','h','H','v','V','f','F','j','J','l','L','i','I','k','K','Escape'].includes(e.key))e.preventDefault();if(e.repeat)return;keys[e.key]=true;if(e.key==='Escape'){if(panelOpen&&started)resume(false);else help('在原野小憩');return;}if(panelOpen)return;const k=e.key.toLowerCase();if(k==='a')attackDown=true;if('123456'.includes(k))selectTool(['hand','pick','spear','hammer','block','bucket'][+k-1]);if(k==='c')craftPanel();if(k==='b')inventoryPanel();if(k==='m')mapPanel();if(k==='e')interact();if(k==='q')skill();if(k==='f')useSecondary();if(k==='j')yaw+=.08;if(k==='l')yaw-=.08;if(k==='i')pitch=Math.min(1.48,pitch+.06);if(k==='k')pitch=Math.max(-1.48,pitch-.06);if(k==='h')goHome();if(k==='v'){third=!third;toast(third?'第三人称：可以看到自己的角色':'第一人称：准星对准目标');}});
document.addEventListener('keyup',e=>{keys[e.key]=false;if(e.key.toLowerCase()==='a')attackDown=false;});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{if(panelOpen)return;canvas.focus?.({preventScroll:true});lookSource='canvas';lastLookX=e.clientX;lastLookY=e.clientY;if(e.button===0){attackDown=true;}if(e.button===2){secondaryPress=true;secondaryUsed=false;mouseMoved=0;if(document.pointerLockElement===canvas){useSecondary();secondaryUsed=true;}else mouseDragging=true;}});document.addEventListener('mouseup',e=>{if(e.button===0){attackDown=false;if(lookSource==='pad')mouseDragging=false;}if(e.button===2){if(secondaryPress&&!secondaryUsed&&!panelOpen){if(mouseMoved<10)useSecondary();else if(['block','bucket'].includes(selected))toast('右键拖动只转视角；看到绿色落点后按 F 放置');}secondaryPress=false;secondaryUsed=false;mouseDragging=false;}});
function moveLook(e){if(panelOpen)return;const locked=document.pointerLockElement===canvas;if(locked||mouseDragging){const dx=locked&&Number.isFinite(e.movementX)?e.movementX:Number.isFinite(e.clientX)&&lastLookX!==null?e.clientX-lastLookX:0;const dy=locked&&Number.isFinite(e.movementY)?e.movementY:Number.isFinite(e.clientY)&&lastLookY!==null?e.clientY-lastLookY:0;yaw-=dx*.0026;pitch=Math.max(-1.48,Math.min(1.48,pitch-dy*.0026));if(mouseDragging)mouseMoved+=Math.abs(dx)+Math.abs(dy);}if(Number.isFinite(e.clientX))lastLookX=e.clientX;if(Number.isFinite(e.clientY))lastLookY=e.clientY;}
document.addEventListener('mousemove',moveLook);
$('lookPad').addEventListener('mousedown',e=>{if(panelOpen)return;e.preventDefault();lookSource='pad';lastLookX=e.clientX;lastLookY=e.clientY;mouseDragging=true;mouseMoved=0;attackDown=false;});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement){expectedPointerUnlock=false;return;}if(expectedPointerUnlock){expectedPointerUnlock=false;return;}if(started&&!panelOpen)help('已暂停 · 鼠标已释放');});
window.addEventListener('blur',()=>{keys={};attackDown=false;if(started&&!panelOpen){pausedByBlur=true;help('已暂停 · 切回继续');}save();});window.addEventListener('beforeunload',save);
$('help').onclick=()=>help('操作与配方');$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){toast('请使用浏览器 F11 全屏');}};
let last=performance.now(),acc=0,uiTimer=0;function tick(dt){time+=dt;yaw+=((keys.j||keys.J?1:0)-(keys.l||keys.L?1:0))*1.7*dt;pitch+=((keys.i||keys.I?1:0)-(keys.k||keys.K?1:0))*1.4*dt;pitch=Math.max(-1.48,Math.min(1.48,pitch));attackCool=Math.max(0,attackCool-dt);skillCool=Math.max(0,skillCool-dt);invulnerable=Math.max(0,invulnerable-dt);movement(dt);updateActors(dt);updateCamera(dt);aim();useAttack(dt);for(const ef of effects){ef.life-=dt;if(ef.ring){ef.mesh.scale.multiplyScalar(1+dt*5);ef.mesh.material.opacity=Math.max(0,ef.life);}else{ef.v.y-=10*dt;ef.mesh.position.addScaledVector(ef.v,dt);}}for(let i=effects.length-1;i>=0;i--)if(effects[i].life<=0){scene.remove(effects[i].mesh);effects[i].mesh.geometry.dispose();if(effects[i].ring)effects[i].mesh.material.dispose();effects.splice(i,1);}if(time>messageUntil)$('toast').hidden=true;uiTimer+=dt;if(uiTimer>.15){hud();uiTimer=0;}saveClock+=dt;if(saveClock>8){save();saveClock=0;}}
function frame(now){GameAudio.setPlaying(!panelOpen);const elapsed=Math.min(.08,(now-last)/1000);last=now;if(!panelOpen){acc+=elapsed;while(acc>=1/90){tick(1/90);acc-=1/90;}}else{updateCamera(0);}updateChunks();updateLabels();renderer.render(scene,camera);requestAnimationFrame(frame);}toolbar();hud();help(stored?'欢迎回到神石原野':'这片原野，属于你');requestAnimationFrame(frame);
