'use strict';
window.RoomClient=class{
 constructor(kind,adapter){this.kind=kind;this.adapter=adapter;this.active=false;this.role=0;this.keys=new Set();this.lastState=0;this.lobby=document.createElement('section');this.lobby.id='room-lobby';document.body.append(this.lobby);this.banner=document.createElement('div');this.banner.id='room-banner';this.banner.hidden=true;document.body.append(this.banner);this.banner.append(document.createElement('span'));const resume=document.createElement('button');resume.textContent='继续';resume.onclick=()=>this.send({type:'pause',value:false});resume.hidden=true;this.banner.append(resume);const leave=document.createElement('button');leave.textContent='离开房间';leave.onclick=()=>this.leave();this.banner.append(leave);this.renderLobby();setInterval(()=>{if(this.active){this.send({type:'input',keys:[...this.keys]});if(Date.now()-this.lastState>5000)this.banner.firstChild.textContent='连接中断，正在重连…';}},100);const reset=()=>{this.keys.clear();this.send({type:'input',keys:[]});};window.addEventListener('blur',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)reset();});}
 renderLobby(error=''){this.lobby.hidden=false;this.lobby.innerHTML='<div class="room-card"><h1>和同伴一起玩</h1><p>① 一人创建房间<br>② 告诉同伴房间码<br>③ 同伴输入房间码加入</p><button id="create-room">创建房间</button><label for="room-code">同伴已经创建好了？</label><input id="room-code" placeholder="6位房间码" maxlength="6" autocomplete="off" aria-label="房间码"><button id="join-room">加入房间</button><p class="room-error" role="status"></p><small>两台手机或电脑打开同一个网址。<br>手机横着拿，左边移动，右边跳跃和使用。</small><button id="local-play">同一台电脑双人玩</button><a href="../">← 回到四款游戏</a></div>';this.lobby.querySelector('.room-error').textContent=error;this.lobby.querySelector('#create-room').onclick=()=>this.connect({create:true});this.lobby.querySelector('#join-room').onclick=()=>{const code=this.lobby.querySelector('input').value.trim().toUpperCase();if(!/^[A-F0-9]{6}$/.test(code)){this.lobby.querySelector('.room-error').textContent='请输入同伴给你的6位房间码';return;}this.connect({code});};this.lobby.querySelector('#local-play').onclick=()=>{this.lobby.hidden=true;this.adapter.local();};}
 connect(join){clearTimeout(this.retry);if(this.ws){this.ws.onclose=null;this.ws.close();}this.join=join;this.lobby.querySelector('.room-error').textContent='正在连接…';const ws=this.ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/room');const timeout=setTimeout(()=>{if(ws.readyState!==WebSocket.OPEN)ws.close();},8000);ws.onopen=()=>{clearTimeout(timeout);this.send({type:'join',game:this.kind,...join});};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='error'){this.active=false;this.banner.hidden=true;this.renderLobby(m.message);ws.onclose=null;ws.close();return;}if(m.type==='joined'){this.active=true;this.role=m.role;this.code=m.code;this.lastState=Date.now();this.join={code:m.code,token:m.token};this.lobby.hidden=true;this.banner.hidden=false;document.body.classList.add('online','role-'+m.role);this.adapter.joined(m.role);}if(m.type==='state'){this.lastState=Date.now();this.running=!m.paused&&m.online.every(Boolean);const names=this.kind==='star'?['科迪','小梅']:['岚 · 盾牌','烁 · 弓箭'];this.banner.firstChild.textContent='房间 '+this.code+' · 你是'+names[this.role]+' · '+(!m.online.every(Boolean)?'等同伴加入…':m.paused?'已暂停':'一起出发！');this.banner.children[1].hidden=!m.paused;this.adapter.state(m);}};ws.onclose=()=>{clearTimeout(timeout);this.keys.clear();this.running=false;if(this.active){this.banner.firstChild.textContent='连接中断，正在重连…';this.retry=setTimeout(()=>this.connect(this.join),1500);}else this.renderLobby('暂时连不上，请确认网址已启动联机服务后再试。');};ws.onerror=()=>{};}
 send(m){if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify(m));}
 input(key,down){if(!this.active)return;if(down)this.keys.add(key);else this.keys.delete(key);this.send({type:'input',keys:[...this.keys]});}
 leave(){this.active=false;this.running=false;clearTimeout(this.retry);if(this.ws){this.ws.onclose=null;this.ws.close();}location.href='../';}
};
