'use strict';
window.TouchControls=function({actions,isPlaying,change,look,player,label}){
 document.body.classList.add('touch-mode');const root=document.createElement('div');root.id=player===undefined?'touch-controls':'touch-controls-player-'+player;root.className='touch-controls';root.hidden=true;if(player!==undefined){root.classList.add('local-player-controls');root.dataset.player=player;root.setAttribute('aria-label',label);const caption=document.createElement('span');caption.className='touch-player-label';caption.textContent=label;root.append(caption);}const pad=document.createElement('div'),buttons=document.createElement('div');pad.className='touch-pad';buttons.className='touch-actions';root.append(pad,buttons);document.body.append(root);const active=new Map();
 function release(id){const item=active.get(id);if(!item)return;active.delete(id);item.button.classList.remove('down');if(![...active.values()].some(x=>x.action===item.action))change(item.action,false);}
 function add(parent,label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',(player===undefined?'':'玩家'+(player+1)+' ')+label);parent.append(b);b.onpointerdown=e=>{e.preventDefault();if(!isPlaying())return;b.setPointerCapture(e.pointerId);active.set(e.pointerId,{button:b,action});b.classList.add('down');change(action,true);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>release(e.pointerId));b.oncontextmenu=e=>e.preventDefault();}
 for(const [label,action]of [['↑','up'],['←','left'],['↓','down'],['→','right']])add(pad,label,action);actions.forEach(([label,action])=>add(buttons,label,action));const clear=()=>[...active.keys()].forEach(release);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
 if(look){let last=null;const canvas=document.querySelector('canvas');canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!isPlaying())return;canvas.setPointerCapture(e.pointerId);last={id:e.pointerId,x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{if(last?.id!==e.pointerId)return;look(e.clientX-last.x,e.clientY-last.y);last.x=e.clientX;last.y=e.clientY;});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>last=null);}
 setInterval(()=>{root.hidden=!isPlaying();if(root.hidden)clear();},100);return{clear};
};
