'use strict';
const {Coop,levels,controls}=StarCoop,$=id=>document.getElementById(id),canvas=$('scene');
let saved={level:0,max:0,muted:false,fireKeys:['ControlRight','ControlLeft']};try{const v=JSON.parse(localStorage.getItem('starbridge.coop.v1'));if(v&&Number.isInteger(v.level))saved={...saved,...v,level:Math.max(0,Math.min(5,v.level)),max:Math.max(0,Math.min(5,v.max||0))};}catch(e){}
const game=new Coop(saved.level);game.fireKeys=Array.isArray(saved.fireKeys)&&saved.fireKeys.length===2?saved.fireKeys:['ControlRight','ControlLeft'];
let mode='menu',held={},pressed={},muted=!!saved.muted,audioContext=null,toastUntil=0,clock=0,last=performance.now(),acc=0,storyPage=0,floorKey='',uiClock=0;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-18,18,11,-11,.1,150);scene.add(new THREE.HemisphereLight(0xe1f0ff,0x45435f,2));const sun=new THREE.DirectionalLight(0xffe4ad,2.8);sun.position.set(-8,20,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;sun.shadow.normalBias=.035;scene.add(sun);
const stage=new THREE.Group(),floorGroup=new THREE.Group(),objectGroup=new THREE.Group(),decor=new THREE.Group(),shotGroup=new THREE.Group();scene.add(stage,shotGroup);stage.add(floorGroup,objectGroup,decor);const mats={};
function material(c){return mats[c]||(mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.86}));}
function mesh(g,geometry,c,x,y,z){const m=new THREE.Mesh(geometry,material(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function box(g,x,y,z,w,h,d,c){return mesh(g,new THREE.BoxGeometry(w,h,d),c,x,y,z);}
function ball(g,x,y,z,rx,ry,rz,c){const m=mesh(g,new THREE.SphereGeometry(1,16,12),c,x,y,z);m.scale.set(rx,ry,rz);return m;}
function cylinder(g,x,y,z,r,h,c){return mesh(g,new THREE.CylinderGeometry(r,r,h,20),c,x,y,z);}
function ring(g,x,y,z,r,c,tube=.055){const m=mesh(g,new THREE.TorusGeometry(r,tube,8,36),c,x,y,z);m.rotation.x=-Math.PI/2;return m;}
function rod(g,a,b,r,c){const d=new THREE.Vector3().subVectors(b,a),m=cylinder(g,(a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2,r,d.length(),c);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return m;}
function limb(g,x,y,z,w,h,c){const p=new THREE.Group();p.position.set(x,y,z);g.add(p);cylinder(p,0,-h/2,0,w,h,c);ball(p,0,-h,0,w*1.12,w*1.12,w*1.12,0xd5ab83);return p;}
function doll(id,ghost=false){const g=new THREE.Group(),cody=id===0;const skin=cody?0xcdb092:0xd9b387,shirt=cody?0xb45343:0xe4bd43;ball(g,0,.87,0,cody?.43:.3,cody?.48:.42,.29,shirt);for(let k=0;k<7;k++)ring(g,0,.55+k*.1,0,cody?.37:.26,cody?0xc76b50:0xf0cd62,.016);const head=ball(g,0,1.5,0,cody?.3:.24,.3,.23,skin);ball(g,0,1.48,.24,cody?.105:.065,.075,.095,skin);for(const x of [-.1,.1]){ball(g,x,1.56,.218,.041,.052,.032,0xf5efe0);ball(g,x,1.56,.244,.019,.026,.016,0x303944);}const mouth=mesh(g,new THREE.TorusGeometry(.065,.014,5,16,Math.PI),0x795b51,0,1.4,.225);mouth.rotation.z=Math.PI;
if(cody){for(let j=0;j<7;j++){const leaf=ball(g,Math.sin(j)*.19,1.84+(j%2)*.08,Math.cos(j)*.1,.09,.19,.045,j%2?0x648846:0x8ca557);leaf.rotation.z=(j-3)*.3;}ball(g,-.24,1.48,0,.07,.11,.06,skin);ball(g,.24,1.48,0,.07,.11,.06,skin);ball(g,.12,.97,.283,.11,.14,.03,0x75895b);for(let i=0;i<3;i++)ball(g,-.1,.74+i*.16,.288,.025,.025,.018,0xe0b88a);}else{ball(g,0,1.72,-.015,.255,.15,.235,0x274a77);ball(g,0,1.98,-.05,.19,.22,.19,0x2a548c);for(let i=0;i<8;i++){const curl=mesh(g,new THREE.TorusGeometry(.16,.023,6,20),0x466d99,0,1.87+i*.024,-.05);curl.rotation.x=i*.3;}for(const x of [-.115,.115]){const glass=mesh(g,new THREE.TorusGeometry(.105,.019,6,24),0x534638,x,1.56,.266);box(g,0,1.57,.267,.055,.025,.02,0x534638);}box(g,0,.63,.02,.49,.08,.48,0x345b87);}
const legs=[limb(g,-.16,.52,0,.11,.42,cody?0xa28e70:0x416c96),limb(g,.16,.52,0,.11,.42,cody?0xa28e70:0x416c96)];for(const x of [-.16,.16])ball(g,x,.075,.09,.145,.085,.23,0x60594e);const arms=[limb(g,cody?-.43:-.32,1.17,0,.09,.43,shirt),limb(g,cody?.43:.32,1.17,0,.09,.43,shirt)];const weapon=new THREE.Group();weapon.position.set(cody?.48:.39,.83,.12);g.add(weapon);const marker=ring(g,0,.018,0,.58,cody?0xeaa26e:0x80c4ef,.035);if(ghost)g.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.42;o.material.color.setHex(0x7bd2ee);}});return{root:g,legs,arms,weapon,marker};}
const dolls=[doll(0),doll(1)];dolls.forEach(d=>scene.add(d.root));let cloneModel=null;
function buildWeapons(){dolls.forEach((d,i)=>{d.weapon.clear();if(game.level<=1){if(i===0){cylinder(d.weapon,0,.12,0,.027,.55,0xc5d0cd);cylinder(d.weapon,0,.43,0,.075,.045,0xc5d0cd);}else{cylinder(d.weapon,0,0,0,.038,.48,0x876d4a);box(d.weapon,0,.29,0,.38,.19,.2,0xa9b9c0);box(d.weapon,-.23,.28,0,.16,.07,.14,0xb5c4cc);}}else if(game.level<=3){box(d.weapon,0,0,.15,.2,.22,.5,i===0?0xdaae49:0x546c87);cylinder(d.weapon,0,.18,.03,.12,.3,i===0?0xf0ca68:0xcf7965);}else if(game.level===4){ring(d.weapon,0,.16,0,.17,i===0?0xf0d478:0x9cd9f2,.04);}else{if(i===0)ball(d.weapon,0,.15,0,.12,.25,.08,0x8aba72);else{cylinder(d.weapon,0,.1,0,.14,.25,0x739cb1);box(d.weapon,0,.15,.2,.08,.08,.32,0x9bc7d0);}}});}
const labelItems=[];function label(root,text,cls='object'){const el=document.createElement('div');el.className='nameLabel '+cls;el.textContent=text;$('labels').appendChild(el);labelItems.push({root,el,cls});return el;}
const nameLabels=dolls.map((d,i)=>label(d.root,i===0?'科迪 · 方向键':'小梅 · WASD',i===0?'cody':'may'));
function cleanup(g){while(g.children.length){const child=g.children.pop();child.traverse(o=>{if(o.geometry)o.geometry.dispose();});child.parent=null;}}
let objectModels={},gate,exitRoot,book,bridgeParticles=[];
function bookModel(){const g=new THREE.Group();box(g,0,.9,0,.9,1.25,.3,0xc84d6a);box(g,.035,.92,0,.79,1.1,.33,0xf0ddb0);box(g,0,.9,.21,.92,1.28,.09,0xc74b64);box(g,-.42,.9,.27,.07,1.25,.08,0xeac974);for(const x of [-.18,.18]){ball(g,x,1.09,.283,.075,.085,.025,0xf6e9c8);ball(g,x,1.08,.31,.03,.04,.012,0x3a404f);}const smile=mesh(g,new THREE.TorusGeometry(.18,.027,6,22,Math.PI),0x763c43,0,.82,.286);smile.rotation.z=Math.PI;for(const x of [-.52,.52]){rod(g,new THREE.Vector3(x,.95,0),new THREE.Vector3(x*1.5,1.27,.1),.055,0xcbae86);ball(g,x*1.5,1.27,.1,.08,.08,.08,0xe6c299);}for(const x of [-.24,.24])rod(g,new THREE.Vector3(x,.32,0),new THREE.Vector3(x,.04,.06),.06,0xcbae86);return g;}
function floorMesh(f){const g=new THREE.Group(),theme=game.config.theme,c=game.config.colors;g.position.set(f.x,f.y-.45,f.z);box(g,0,-.2,0,f.w,.9,f.d,c[1]);box(g,0,.36,0,f.w,.18,f.d,c[2]);if(f.id.startsWith('leaf')){box(g,0,.48,0,f.w*.94,.12,f.d*.95,0x91ba64);for(let z=-1;z<=1;z++)box(g,0,.55,z,.05,.02,1.7,0xb5d887);}else for(let x=-f.w/2+.55;x<f.w/2;x+=1.15){box(g,x,.457,0,.025,.015,f.d,theme==='clock'?0x987343:0x8c704f);}for(const x of [-f.w/2+.3,f.w/2-.3])for(const z of [-f.d/2+.3,f.d/2-.3])cylinder(g,x,.5,z,.055,.02,0x5c6667);floorGroup.add(g);}
function updateFloors(){const fs=game.floors(),key=fs.map(f=>f.id+f.y).join('|');if(key===floorKey)return;floorKey=key;cleanup(floorGroup);fs.forEach(floorMesh);}
const descriptions={pin:'科迪 · 投钉固定',hammer:'小梅 · 锤击按钮',nail:'科迪 · 打入挂钉',swing:'小梅 · 锤爪摆荡',release:'小梅 · 敲击接桥',pan:'树液配重盘 0/3',resin:'树液 + 火柴',wasp0:'黄蜂护甲',wasp1:'黄蜂护甲',wasp2:'黄蜂护甲',time:'科迪 · 倒转时间',clone:'小梅 · 留下分身',soil:'科迪 · 藤蔓化身',water:'小梅 · 浇水',weed:'小梅 · 镰刀割草'};
function buildObject(o){const g=new THREE.Group();g.position.set(o.x,o.y,o.z);const color=o.owner===0?0xe6a168:o.owner===1?0x86c9e5:0xf0d992;const halo=ring(g,0,-o.y+.03,0,o.id==='soil'||o.id==='water'?.95:.75,color,.035);if(o.type==='nail'){box(g,0,.35,0,.7,.85,.2,0xf3cc60);const r=ring(g,0,.5,.13,.2,0x7b6044,.035);r.rotation.x=0;cylinder(g,0,.13,.18,.04,.4,0xa8bcc6);}else if(o.type==='hammer'){cylinder(g,0,.13,0,.55,.26,0x665c54);cylinder(g,0,.32,0,.41,.2,0xf0c452);}else if(o.type==='hook'){const r=ring(g,0,.75,0,.3,0xcad9d3,.08);r.rotation.x=0;box(g,0,.12,0,.5,.25,.5,0x77706c);}else if(o.type==='sapPan'){cylinder(g,0,.2,0,.75,.18,0x65706c);rod(g,new THREE.Vector3(0,.2,0),new THREE.Vector3(0,2,0),.045,0xd9c797);}else if(o.type==='resin'||o.type==='weed'){for(let i=0;i<7;i++){const v=ball(g,Math.sin(i*2)*.6,i*.18,Math.cos(i*2)*.3,.3,.6,.2,o.type==='resin'?0x765443:0x655678);v.rotation.z=Math.sin(i)*.7;}}else if(o.type==='wasp'){ball(g,0,.3,0,.6,.44,.38,0xd3ad52);for(const x of [-.32,0,.32])box(g,x,.35,.02,.08,.76,.66,0x504d43);ball(g,.5,.3,0,.25,.3,.3,0x625d4d);const wings=[ball(g,-.1,.7,.45,.45,.035,.32,0xc9e1d8),ball(g,-.1,.7,-.45,.45,.035,.32,0xc9e1d8)];g.userData.wings=wings;}else if(o.type==='clock'){const r=ring(g,0,.7,0,.65,0xe7c775,.12);r.rotation.x=0;box(g,0,.7,.08,.05,.8,.05,0xd6e0cc);box(g,.18,.7,.08,.4,.05,.05,0xd6e0cc);}else if(o.type==='clone'){cylinder(g,0,.08,0,.8,.15,0x76abc2);ring(g,0,.2,0,.6,0xbcecff,.04);}else if(o.type==='soil'||o.type==='water'){if(o.type==='soil'){cylinder(g,0,.05,0,.9,.1,0x725e47);ball(g,0,.4,0,.16,.38,.1,0x8cac61);}}
g.userData.halo=halo;objectGroup.add(g);objectModels[o.id]=g;label(g,descriptions[o.id]);}
function gear(g,x,y,z,r){const h=new THREE.Group();h.position.set(x,y,z);const circle=ring(h,0,0,0,r,0xc4a05f,.18);circle.rotation.x=0;for(let i=0;i<12;i++){const a=i/12*Math.PI*2,m=box(h,Math.cos(a)*r,Math.sin(a)*r,0,.25,.34,.18,0xc4a05f);m.rotation.z=a;}g.add(h);return h;}
const decorations=[];function buildStage(){cleanup(floorGroup);cleanup(objectGroup);cleanup(decor);floorKey='';objectModels={};for(let i=labelItems.length-1;i>=2;i--){labelItems[i].el.remove();labelItems.splice(i,1);}if(cloneModel){scene.remove(cloneModel.root);cloneModel=null;}decorations.length=0;scene.background=new THREE.Color(game.config.colors[0]);scene.fog=new THREE.Fog(game.config.colors[0],36,85);updateFloors();game.config.objects.forEach(buildObject);
gate=new THREE.Group();const obs=game.obstacles()[0];gate.position.set(obs?obs.x:6,0,0);for(let z=-5.5;z<=5.5;z+=1.1){box(gate,0,1.3,z,.3,2.6,.55,game.config.theme==='tree'?0x795747:0x9f8265);box(gate,0,1,z,.39,.08,.61,0xe3bd80);}decor.add(gate);
exitRoot=new THREE.Group();exitRoot.position.set(game.config.exit[0],0,game.config.exit[1]);const arch=mesh(exitRoot,new THREE.TorusGeometry(1.7,.13,10,48,Math.PI),0xd6e3b0,0,.15,0);box(exitRoot,-1.7,.2,0,.25,.6,.3,0xd6e3b0);box(exitRoot,1.7,.2,0,.25,.6,.3,0xd6e3b0);ring(exitRoot,0,.06,0,1.75,0xd6e3b0,.07);decor.add(exitRoot);label(exitRoot,'两人一起到达');
book=bookModel();book.position.set(-9,.1,0);decor.add(book);label(book,'哈金博士');
if(game.config.theme==='shed'){for(let i=0;i<7;i++){const g=new THREE.Group();g.position.set(-10+i*3.4,-.02,-6.9);cylinder(g,0,.6,0,.38,1.2,i%2?0xa1b0b4:0xc89c77);cylinder(g,0,1.25,0,.55,.12,0xb9b7a7);cylinder(g,0,.02,0,.55,.12,0xb9b7a7);decor.add(g);}box(decor,0,-4,0,35,.5,23,0x2f3846);}else if(game.config.theme==='tree'||game.config.theme==='garden'){for(let i=0;i<10;i++){const x=-13+i*2.9,z=(i%2?1:-1)*7.7;const trunk=cylinder(decor,x,1,z,.45,3,0x756146);ball(decor,x,3.3,z,1.7,1.4,1.6,game.config.theme==='garden'?0x7ea95f:0x527d58);for(let j=0;j<3;j++){const flower=ball(decor,x+.7+j*.27,.12,z-.8,.12,.14,.12,[0xeac65c,0xf2a38c,0xacc8e3][j]);}}}else{for(let i=0;i<7;i++)decorations.push(gear(decor,-10+i*3.4,2.5,-7,1+i%2*.4));for(let i=0;i<4;i++)box(decor,-10+i*6,1,-6.8,.35,3,.5,0xb69a68);}
buildWeapons();updateUI();}
function ability(i){return game.level<=1?(i===0?'投钉':'锤子'):game.level<=3?(i===0?'树液枪':'火柴枪'):game.level===4?(i===0?'时间回溯':'分身'):(i===0?'藤蔓化身':'水壶 / 镰刀');}
function fireLabel(i){return game.fireKeys[i]==='ControlRight'?'Enter / 右Ctrl':game.fireKeys[i]==='ControlLeft'?'左Ctrl':game.fireKeys[i]==='Slash'?'/':game.fireKeys[i]==='KeyC'?'C':game.fireKeys[i];}
function updateUI(){$('levelTitle').textContent=String(game.level+1).padStart(2,'0')+' / 06　'+game.config.name;$('goal').textContent=game.goal;$('mechanisms').innerHTML=game.status().map(s=>'<span>'+s+'</span>').join('');$('codyControls').innerHTML='<b>科迪 · '+ability(0)+(game.players[0].ready?' ✓ 已准备':'')+'</b><div class="keys"><kbd>↑ ↓ ← →</kbd> 移动 <kbd>空格</kbd> 跳<br><kbd>右Shift</kbd> 准备 <kbd>'+fireLabel(0)+'</kbd> 点按使用</div>';$('mayControls').innerHTML='<b>小梅 · '+ability(1)+(game.players[1].ready?' ✓ 已准备':'')+'</b><div class="keys"><kbd>W A S D</kbd> 移动 <kbd>X</kbd> 跳<br><kbd>左Shift</kbd> 准备 <kbd>'+fireLabel(1)+'</kbd> 点按使用</div>';$('mute').textContent=muted?'♪ 已静音':'♪ 音效开';}
function sound(type){GameAudio.sfx(type);}
function toast(s){if(!s)return;$('toast').textContent=s;$('toast').hidden=false;toastUntil=clock+5;}
function save(){saved={...saved,level:mode==='complete'?saved.level:game.level,muted,fireKeys:game.fireKeys};try{localStorage.setItem('starbridge.coop.v1',JSON.stringify(saved));}catch(e){}}
function show(html,newMode='pause'){mode=newMode;held={};pressed={};$('panel').hidden=false;$('panel').innerHTML='<div class="sheet">'+html+'</div>';}
function play(){mode='play';held={};pressed={};$('panel').hidden=true;canvas.focus();sound('prepare');}
function start(level=0,story=false){game.load(level);buildStage();save();if(story){storyPage=0;showStory();}else play();}
const stories=[['哈金博士','嘿，科迪、小梅！你们又回到了这本书里。这次不需要争论谁走得快，只要一起修好六段小小的回忆。'],['小梅与科迪','小梅说：“我的锤子能把挡板抬起来。”科迪举起钉子：“那我就把它固定住。你先来，我按 Enter 接上！”'],['哈金博士','从棚屋到树洞，再到钟楼和花园。每一条路都需要两个人，光门也会等你们一起到达。出发吧！']];
function showStory(){const [speaker,text]=stories[storyPage];show('<div class="eyebrow">新编开场 · '+(storyPage+1)+' / 3</div><h2>'+speaker+'</h2><p>'+text+'</p><div class="row"><button class="primary" id="nextStory">'+(storyPage===2?'开始合作':'继续故事')+'</button><button id="skipStory">按 A 跳过剧情</button></div><p class="small">只有剧情期间 A 用于跳过；进入游戏后 A 是小梅向左移动。科迪用 Enter 使用能力，小梅用左Ctrl。</p>','story');$('nextStory').onclick=()=>{if(++storyPage>=stories.length)play();else showStory();};$('skipStory').onclick=play;}
function menu(){show('<div class="eyebrow">同一电脑 · 两位玩家 · 真正3D</div><h1>星桥搭档</h1><p>科迪与小梅的六段合作试炼。一起投钉、摆荡、引爆树液、倒转时间，让花园重新长出道路。</p><div class="grid"><div class="tile"><h3 style="color:#ffbc8c">科迪</h3><p>方向键移动 · 空格跳跃<br>右Shift 准备 · Enter / 右Ctrl 点按使用</p></div><div class="tile"><h3 style="color:#a9d8f5">小梅</h3><p>WASD 移动 · X 跳跃<br>左Shift 准备 · 左Ctrl 点按使用</p></div><div class="tile"><h3>一起玩</h3><p>自动跟随镜头，无需鼠标<br>机关分工，落下就近回来<br>两个人都到终点才过关</p></div></div><div class="row"><button class="primary" id="new">从棚屋开始</button><button id="continue">继续第 '+(saved.level+1)+' 关</button><button id="levels">选关</button><button id="options">按键设置</button><button id="fsMenu">⛶ 全屏</button></div><p class="small">Shift 按一下准备即可。Ctrl 只点按，松开后再移动；科迪没有右Ctrl也能用 Enter；还可在设置改为 C 和 /。</p><p class="small">基于《双人成行》角色与章节机制制作的非官方简化练习版。角色、场景和游戏逻辑自制，渲染使用 Three.js；不是原版完整游戏。</p>','menu');$('new').onclick=()=>start(0,true);$('continue').onclick=()=>start(saved.level);$('levels').onclick=levelMenu;$('options').onclick=options;$('fsMenu').onclick=fullscreen;}
function levelMenu(){show('<h2>六段合作回忆</h2><div class="grid">'+levels.map((l,i)=>'<button class="tile" data-level="'+i+'" '+(i>saved.max?'disabled':'')+'><h3>'+String(i+1).padStart(2,'0')+' '+l.name+'</h3><p>'+l.chapter+'</p><p>'+(i>saved.max?'通过前面的关卡后解锁':'进入 / 重玩')+'</p></button>').join('')+'</div><div class="row"><button id="back">返回</button></div>');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(+b.dataset.level));$('back').onclick=menu;}
function options(){show('<h2>键盘与双人输入</h2><p>默认：小梅左Shift准备、左Ctrl使用；科迪右Shift准备、Enter使用（右Ctrl也可）。系统会区分左右按键，两人不会触发对方的能力。</p><p>没有右Ctrl时，科迪直接按Enter即可。如果需要额外替代键，可改成小梅 C、科迪 / 使用能力。移动、跳跃、左右Shift准备保持不变。</p><div class="row"><button id="defaultKeys">使用默认按键</button><button id="safeKeys">使用 C 和 /</button><button id="back">返回游戏</button></div><p class="small">当前：小梅 '+fireLabel(1)+'；科迪 '+fireLabel(0)+'。不要按住 Ctrl 再按 W 等字母键，避免浏览器快捷键。部分键盘不支持很多键同时按；机关已设计为点按锁定。</p>');$('defaultKeys').onclick=()=>{game.fireKeys=['ControlRight','ControlLeft'];save();updateUI();options();};$('safeKeys').onclick=()=>{game.fireKeys=['Slash','KeyC'];save();updateUI();options();};$('back').onclick=play;}
function pause(){if(mode==='play'){show('<h2>休息一下</h2><p>'+game.config.hint+'</p><div class="row"><button class="primary" id="resume">继续合作</button><button id="retry">重试本关</button><button id="options">按键设置</button><button id="levels">选择关卡</button></div>');$('resume').onclick=play;$('retry').onclick=()=>start(game.level);$('options').onclick=options;$('levels').onclick=levelMenu;}else if(mode==='pause')play();}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){toast('可使用浏览器 F11 全屏');}}
const effects=[];function explosion(x,y,z){for(let i=0;i<24;i++){const g=ball(scene,x,y+.5,z,.09,.09,.09,i%2?0xf7cf7c:0xe6a66b);effects.push({g,v:new THREE.Vector3((Math.random()-.5)*6,Math.random()*6,(Math.random()-.5)*6),life:.7});}}
game.onEvent=e=>{if(e.type==='load')return;sound(e.type);if(e.text)toast(e.text);if(e.type==='explode')explosion(e.x,e.y,e.z);if(e.type==='complete'){saved.max=Math.min(5,Math.max(saved.max,game.level+1));saved.level=Math.min(5,game.level+1);try{localStorage.setItem('starbridge.coop.v1',JSON.stringify({...saved,muted,fireKeys:game.fireKeys}));}catch(e){}if(game.level===5){show('<div class="eyebrow">六段回忆 · 一起完成</div><h1>我们一起做到了</h1><p>哈金博士合上书，轻声说：“路不是等来的，是你们替对方搭出来的。”<br>棚屋、树洞、钟楼与花园，都留下了你们合作的痕迹。</p><div class="row"><button class="primary" id="replay">再玩一次</button><button id="choose">重玩某一关</button></div>','complete');$('replay').onclick=()=>start(0,true);$('choose').onclick=levelMenu;}else{show('<div class="eyebrow">两个人都到达了</div><h2>'+game.config.name+' · 完成</h2><p>下一段：'+levels[game.level+1].name+'<br>这一关就近救回 '+game.deaths+' 次，合作成功最重要。</p><div class="row"><button class="primary" id="next">一起进入下一关</button><button id="repeat">重玩本关</button></div>','complete');$('next').onclick=()=>start(game.level+1);$('repeat').onclick=()=>start(game.level);}}updateUI();};
const controlled=new Set([...controls.flatMap(c=>[c.left,c.right,c.up,c.down,c.jump,c.ready,c.fire]),'KeyC','Slash','Enter','NumpadEnter']);
document.addEventListener('keydown',e=>{if(mode==='story'&&e.code==='KeyA'){e.preventDefault();play();return;}if(e.code==='Escape'){e.preventDefault();pause();return;}if(mode!=='play')return;if((e.code==='Enter'||e.code==='NumpadEnter')&&e.repeat){e.preventDefault();return;}if(controlled.has(e.code)||e.ctrlKey)e.preventDefault();if(!held[e.code])pressed[e.code]=true;held[e.code]=true;});document.addEventListener('keyup',e=>{held[e.code]=false;});window.addEventListener('blur',()=>{held={};pressed={};if(mode==='play')pause();});window.addEventListener('beforeunload',save);
$('fullscreen').onclick=fullscreen;$('pause').onclick=pause;$('mute').onclick=()=>{muted=!muted;save();updateUI();};
function animateWorld(dt){updateFloors();const f=game.flags;gate.visible=game.obstacles().length>0;gate.position.y=game.level===0&&f.raisedUntil>game.t?-1.7:0;exitRoot.children.forEach(o=>{if(o.material)o.material.emissive?.setHex(game.ready()?0x284829:0x000000);});book.position.y=.15+Math.sin(clock*2)*.13;book.rotation.y=Math.sin(clock)*.1;decorations.forEach((g,i)=>g.rotation.z+=(game.flags.timeUntil>game.t?-1:1)*dt*(i%2?.25:-.2));
for(const o of game.config.objects){const m=objectModels[o.id];m.visible=!(o.type==='wasp'&&f[o.id+'dead'])&&!(o.id==='resin'&&f.burn)&&!(o.id==='weed'&&f.weed);let highlight=game.players.some(p=>p.ready&&game.target(p)?.id===o.id);m.userData.halo.scale.setScalar(highlight?1.1+Math.sin(clock*5)*.05:1);m.userData.halo.material.emissive?.setHex(highlight?0x665626:0);if(o.type==='wasp'){m.position.y=o.y+Math.sin(clock*3+o.x)*.15;m.userData.wings.forEach((w,i)=>w.rotation.x=Math.sin(clock*30)*(i?-.3:.3));if(f[o.id+'sap'])m.children[1].material=material(0xeab348);}if(o.id==='resin'&&f.resin)m.children.slice(1).forEach(c=>c.material=material(0xd39e45));if(o.id==='pan'){m.position.y=o.y-Math.min(3,f.pan||0)*.15;const tag=labelItems.find(l=>l.root===m);if(tag)tag.el.textContent='树液配重盘 '+Math.min(3,f.pan||0)+'/3';}}
if(f.clone&&!cloneModel){cloneModel=doll(1,true);cloneModel.root.position.set(f.clone.x,0,f.clone.z);scene.add(cloneModel.root);label(cloneModel.root,'小梅的分身');}
dolls.forEach((d,i)=>{const p=game.players[i];d.root.visible=!p.recover;d.root.position.set(p.x,p.y,p.z);d.root.rotation.y=p.face;const speed=Math.hypot(p.vx,p.vz);d.legs[0].rotation.x=Math.sin(game.t*11)*Math.min(.65,speed*.14);d.legs[1].rotation.x=-d.legs[0].rotation.x;d.arms[0].rotation.x=-d.legs[0].rotation.x*.6;d.arms[1].rotation.x=p.anim>0?-1.3: d.legs[0].rotation.x*.6;d.weapon.visible=p.ready;d.root.scale.setScalar(p.rooted?.65:1);nameLabels[i].textContent=(i===0?'科迪':'小梅')+(p.recover?' · 正在回来':p.ready?' · '+ability(i):' · 按'+(i===0?'右':'左')+'Shift');});
cleanup(shotGroup);for(const s of game.shots){if(game.level<=1){const n=cylinder(shotGroup,s.x,s.y,s.z,.035,.42,0xc9d5d1);n.rotation.z=Math.PI/2;}else ball(shotGroup,s.x,s.y,s.z,.14,.14,.14,game.level===5?0x7cd6ee:s.from===0?0xf0bb4f:0xffaa79);}
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.v.y-=8*dt;e.g.position.addScaledVector(e.v,dt);if(e.life<=0){scene.remove(e.g);e.g.geometry.dispose();effects.splice(i,1);}}
}
let cameraCenter=new THREE.Vector3(-6,0,0),viewHalf=9;
function updateCamera(dt){const [a,b]=game.players,mid=new THREE.Vector3((a.x+b.x)/2,0,(a.z+b.z)/2),aspect=innerWidth/innerHeight;cameraCenter.lerp(mid,Math.min(1,dt*4));const needed=Math.max(7.5,(Math.abs(a.x-b.x)+12)/(2*aspect),Math.abs(a.z-b.z)*.45+6);viewHalf+= (needed-viewHalf)*Math.min(1,dt*4);camera.left=-viewHalf*aspect;camera.right=viewHalf*aspect;camera.top=viewHalf;camera.bottom=-viewHalf;camera.updateProjectionMatrix();camera.position.set(cameraCenter.x,20,cameraCenter.z+17);camera.lookAt(cameraCenter.x,0,cameraCenter.z);camera.updateMatrixWorld();const p=new THREE.Vector3();for(const l of labelItems){l.root.getWorldPosition(p);p.y+=l.cls==='object'?1.3:2.35;p.project(camera);l.el.style.left=Math.max(16,Math.min(innerWidth-16,(p.x*.5+.5)*innerWidth))+'px';l.el.style.top=Math.max(65,Math.min(innerHeight-100,(-p.y*.5+.5)*innerHeight))+'px';l.el.hidden=l.cls==='object'&&(mode!=='play'||!l.root.visible||Math.abs(p.x)>1.1||Math.abs(p.y)>1.1);}}
window.addEventListener('resize',()=>renderer.setSize(innerWidth,innerHeight));
function frame(now){GameAudio.setPlaying(mode==='play'&&!game.finished&&(typeof net==='undefined'||!net.active||net.running));const elapsed=Math.min(.08,(now-last)/1000);last=now;clock+=elapsed;if(mode==='play'){acc+=elapsed;while(acc>=1/90){game.tick(1/90,held,pressed);pressed={};acc-=1/90;}uiClock+=elapsed;if(uiClock>.15){updateUI();uiClock=0;}}else acc=0;animateWorld(elapsed);updateCamera(elapsed);if(clock>toastUntil)$('toast').hidden=true;renderer.render(scene,camera);requestAnimationFrame(frame);}
buildStage();menu();requestAnimationFrame(frame);
// Expose only the same visible navigation and status actions to compatible browser assistants.
if(document.modelContext?.registerTool){for(const tool of [{name:'read_coop_status',description:'Read current level, cooperation progress and both players without changing the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,level:game.level+1,name:game.config.name,status:game.status(),players:game.players.map(p=>({name:p.id===0?'科迪':'小梅',x:p.x,y:p.y,z:p.z,ready:p.ready}))})},{name:'open_coop_help',description:'Pause this local cooperative game and show its keyboard settings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{options();return{mode,shown:'keyboard settings'};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch(e){}}}
