(function(root){'use strict';
const rect=(id,x,z,w,d,y=0)=>({id,x,z,w,d,y}),obj=(id,type,x,z,owner,y=0)=>({id,type,x,z,owner,y});
const levels=[
{name:'棚屋 · 锤钉试炼',chapter:'The Shed · The Depths',theme:'shed',colors:[0x203949,0xa77f52,0xe5bd83],spawn:[[-8,-2.5],[-8,2.5]],floors:[rect('bench',0,0,24,13)],objects:[obj('pin','nail',-4,-2.5,0,1),obj('hammer','hammer',-4,2.5,1)],exit:[9,0],goal:'小梅走近黄色按钮，用锤子抬起挡板；科迪在6秒内投钉固定它。',hint:'先各按一次自己的 Shift 准备。小梅用 D 走近按钮，再点左 Ctrl；科迪点 Enter（或右 Ctrl）。'},
{name:'棚屋 · 钉头摆渡',chapter:'The Shed · Wired Up',theme:'shed',colors:[0x294356,0x9a785a,0xebc88c],spawn:[[-9,-2],[-8,2]],floors:[rect('left',-8,0,8,12),rect('right',7,0,10,12)],objects:[obj('nail','nail',-3,0,0,2),obj('swing','hook',-4.7,0,1),obj('release','hammer',5,0,1)],exit:[10,0],goal:'科迪投钉造出挂点；小梅走到边缘钩环，用锤爪摆到对岸，再敲按钮接回科迪。',hint:'钩环在左岸边缘。小梅靠近后点左 Ctrl 自动抓钉摆荡；落地后再敲黄色按钮。'},
{name:'大树 · 树液配重',chapter:'The Tree · Captured',theme:'tree',colors:[0x173d40,0x6f9860,0xd8b870],spawn:[[-9,-2],[-9,2]],floors:[rect('left',-8,0,8,12),rect('right',6.5,0,11,12)],objects:[obj('pan','sapPan',-5,0,0,1),obj('resin','resin',5.5,0,null,1)],exit:[10,0],goal:'科迪向配重盘射3团树液，压出树枝桥；过桥后给树脂障碍涂树液，小梅用火柴点燃。',hint:'树液是橙色的。火柴单独不能炸开障碍，需要先由科迪涂上树液。'},
{name:'大树 · 黄蜂哨所',chapter:'The Tree · Deeply Rooted',theme:'tree',colors:[0x244b48,0x819c62,0xe0c27d],spawn:[[-9,-2],[-9,2]],floors:[rect('arena',0,0,24,14)],objects:[obj('wasp0','wasp',-1,-3,null,1),obj('wasp1','wasp',1,0,null,1),obj('wasp2','wasp',-1,3,null,1)],exit:[9,0],goal:'科迪给黄蜂护甲涂树液，小梅射火柴引爆。三只黄蜂都清除后，一起穿过树洞门。',hint:'两人的武器会自动选附近合适目标，不用争抢鼠标。靠近到7格内再点 Ctrl。'},
{name:'布谷鸟钟 · 时间之门',chapter:'Cuckoo Clock · Gates of Time',theme:'clock',colors:[0x2d3151,0xa99367,0xf1d9a0],spawn:[[-9,-2],[-9,2]],floors:[rect('left',-8,0,8,12),rect('right',7,0,10,12)],objects:[obj('time','clock',-6,-2,0,1),obj('clone','clone',4,1.8,1)],exit:[10,0],goal:'科迪倒转时间修复断桥；小梅过桥，在蓝色踏板留下分身，把时间门固定住。',hint:'修复桥维持10秒，科迪可再次使用能力延长。小梅的分身留在踏板上后，两人都能过门。'},
{name:'花园 · 藤蔓与水',chapter:'The Garden · Green Fingers',theme:'garden',colors:[0x234d50,0x8ca66b,0xe6c888],spawn:[[-9,-2],[-9,2]],floors:[rect('left',-8.5,0,7,12),rect('right',8.5,0,7,12)],objects:[obj('soil','soil',-6,0,0),obj('water','water',-6,0,1),obj('weed','weed',8,0,1)],exit:[11,0],goal:'科迪在土坑化为藤蔓，小梅浇水3次让叶片长成平台，再跳过花园割开杂草。',hint:'科迪扎根时暂时不能移动。小梅用 D 和 X 跳过叶片，到对岸使用镰刀，科迪就能恢复并跟上。'}
];
const controls=[{left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown',jump:'Space',ready:'ShiftRight',fire:'ControlRight'},{left:'KeyA',right:'KeyD',up:'KeyW',down:'KeyS',jump:'KeyX',ready:'ShiftLeft',fire:'ControlLeft'}];
const inside=(x,z,r,m=0)=>Math.abs(x-r.x)<=r.w/2+m&&Math.abs(z-r.z)<=r.d/2+m;
class Coop{
constructor(level=0){this.onEvent=()=>{};this.fireKeys=['ControlRight','ControlLeft'];this.load(level);}
load(n){this.level=n;this.config=levels[n];this.t=0;this.flags={};this.shots=[];this.finished=false;this.finishTime=0;this.deaths=0;this.goal=this.config.goal;this.players=this.config.spawn.map(([x,z],i)=>({id:i,x,y:0,z,vx:0,vy:0,vz:0,ground:true,face:0,ready:false,cool:0,checkpoint:{x,y:0,z},recover:0,tween:null,rooted:false,anim:0}));this.emit('load');}
emit(type,text,extra={}){this.onEvent({type,text,...extra});}
floors(){const r=this.config.floors.slice(),f=this.flags;if(this.level===1&&f.release)r.push(rect('bridge',-1,0,6,2.8));if(this.level===2&&(f.pan||0)>=3)r.push(rect('branch',-1.5,0,5,3));if(this.level===4&&(f.timeUntil>this.t||f.clone))r.push(rect('timeBridge',-1,0,6,3));if(this.level===5&&(f.water||0)>=3)r.push(rect('leafA',-3.5,0,2.4,3,.45),rect('leafB',-.5,0,2.4,3,.9),rect('leafC',2.5,0,2.4,3,.45));return r;}
obstacles(){let closed=false,x=6;if(this.level===0){closed=!this.flags.pin;x=1;}if(this.level===2){closed=!this.flags.burn;x=7;}if(this.level===3)closed=!this.ready();if(this.level===4){closed=!this.flags.clone;x=7;}if(this.level===5){closed=!this.flags.weed;x=9;}return closed?[{...rect('gate',x,0,.55,this.level===3?14:12),height:3.5}]:[];}
blocked(x,y,z){return this.obstacles().some(r=>inside(x,z,r,.27)&&y<r.height);}
groundAt(x,z,maxY=100){return this.floors().filter(f=>inside(x,z,f,.1)&&f.y<=maxY).sort((a,b)=>b.y-a.y)[0]||null;}
checkpoint(p,x,y,z){p.checkpoint={x,y,z};}
availableTarget(p,o){const f=this.flags;if(o.owner!==null&&o.owner!==p.id)return false;switch(o.id){case'hammer':return !f.pin;case'pin':return !f.pin;case'nail':return !f.nail;case'swing':return !f.swung;case'release':return f.swung&&!f.release;case'pan':return(f.pan||0)<3;case'resin':return(f.pan||0)>=3&&!f.burn&&(p.id===1||!f.resin);case'time':return !f.clone;case'clone':return !f.clone;case'soil':return !f.soil;case'water':return f.soil&&(f.water||0)<3;case'weed':return(f.water||0)>=3&&!f.weed;default:if(o.type==='wasp')return !f[o.id+'dead']&&(p.id===1||!f[o.id+'sap']);return true;}}
target(p){let choices=this.config.objects.filter(o=>this.availableTarget(p,o));if(this.level===3&&p.id===1)choices.sort((a,b)=>(!!this.flags[b.id+'sap'])-(!!this.flags[a.id+'sap']));const range=(this.level<=1&&p.id===1)||this.level===4&&p.id===1||this.level===5?2.8:7.5;const valid=choices.filter(o=>Math.hypot(p.x-o.x,p.z-o.z)<range&&Math.abs(p.y-o.y)<3);if(this.level!==3||p.id!==1)valid.sort((a,b)=>Math.hypot(p.x-a.x,p.z-a.z)-Math.hypot(p.x-b.x,p.z-b.z));return valid[0]||null;}
fire(i){const p=this.players[i];if(p.recover||p.tween||p.cool>0)return;if(!p.ready){this.emit('hint',(i===0?'科迪：先点右 Shift':'小梅：先点左 Shift')+'准备能力，再点 Ctrl 使用');return;}const target=this.target(p);if(!target){this.emit('hint','再靠近自己的机关或目标一点；高亮圆圈是当前目标');return;}p.cool=.42;p.anim=.3;if(['nail','sapPan','resin','wasp','water'].includes(target.type)){this.shots.push({x:p.x,y:p.y+.9,z:p.z,from:i,to:target.id,life:1.5});this.emit('shot',null,{player:i});}else this.hit(i,target.id);}
hit(i,id){const f=this.flags,p=this.players[i];if(id==='hammer'){f.raisedUntil=this.t+6;this.goal='挡板抬起来了！科迪点 Enter（或右 Ctrl） 把钉子打入橙色靶心。';}
if(id==='pin'){if(!(f.raisedUntil>this.t)){this.emit('hint','请小梅先靠近黄色按钮，用锤子抬起挡板');return;}f.pin=true;this.goal='钉子固定成功！两人一起走到右侧光门。';this.players.forEach(p=>this.checkpoint(p,3,0,p.id===0?-1:1));}
if(id==='nail'){f.nail=true;this.goal='挂钉就绪！小梅走到边缘钩环，使用锤爪抓住它摆过去。';}
if(id==='swing'){if(!f.nail){this.emit('hint','先让科迪把钉子打进黄色靶心');return;}f.swung=true;p.tween={start:{x:p.x,y:p.y,z:p.z},end:{x:4,y:0,z:0},t:0,duration:1.7,arc:3};this.goal='小梅摆到对岸了！靠近黄色按钮用锤子接通桥梁。';this.checkpoint(p,4,0,1);}
if(id==='release'){f.release=true;this.goal='桥已放下！科迪过桥，两人一起到光门。';this.players.forEach(p=>this.checkpoint(p,4,0,p.id===0?-1:1));}
if(id==='pan'){f.pan=(f.pan||0)+1;this.goal=f.pan>=3?'树枝桥落下了！科迪给对岸树脂涂树液，小梅再点火。':'配重盘已涂 '+f.pan+'/3 团树液，科迪继续发射。';}
if(id==='resin'){if(i===0){f.resin=true;this.goal='树脂已经涂好！小梅用火柴引爆它。';}else if(f.resin){f.burn=true;this.goal='障碍炸开了！两人一起进入树洞门。';this.emit('explode',null,{x:5.5,y:1,z:0});this.players.forEach(p=>this.checkpoint(p,3,0,p.id===0?-1:1));}else{this.emit('hint','火柴需要树液：先让科迪给障碍涂上橙色树液');return;}}
if(id.startsWith('wasp')){if(f[id+'dead'])return;if(i===0)f[id+'sap']=true;else if(f[id+'sap']){f[id+'dead']=true;const o=this.config.objects.find(o=>o.id===id);this.emit('explode',null,o);this.goal=this.ready()?'黄蜂全部清除！两人到右侧光门会合。':'护甲爆开了！继续树液加火柴，清除剩下的黄蜂。';}else{this.emit('hint','护甲还没有树液，火柴暂时无效');return;}}
if(id==='time'){f.timeUntil=this.t+10;this.goal='断桥已倒回完好状态，维持10秒！小梅过桥在蓝色踏板留下分身。';}
if(id==='clone'){f.clone={x:4,y:0,z:1.8};this.goal='小梅的分身压住了踏板，时间门已固定！两人一起通过。';this.players.forEach(p=>this.checkpoint(p,4,0,p.id===0?-1:1));}
if(id==='soil'){f.soil=true;p.rooted=true;p.x=-6;p.z=0;p.y=0;this.goal='科迪化成了藤蔓！小梅靠近土坑，使用水壶浇水3次。';}
if(id==='water'){f.water=(f.water||0)+1;this.goal=f.water>=3?'叶片长好了！小梅用 D 和 X 跳过叶片，到对岸挥镰刀清除杂草。':'浇水 '+f.water+'/3：小梅继续使用水壶。';}
if(id==='weed'){f.weed=true;this.players[0].rooted=false;this.goal='花园恢复了！科迪跟上，一起跨过最后的光门。';this.checkpoint(this.players[1],7,0,1);}
this.emit('mechanism',this.goal);}
ready(){const f=this.flags;return[this.level===0&&f.pin,this.level===1&&f.release,this.level===2&&f.burn,this.level===3&&[0,1,2].every(i=>f['wasp'+i+'dead']),this.level===4&&f.clone,this.level===5&&f.weed].some(Boolean);}
recover(p){if(p.recover)return;p.recover=.75;p.vy=0;this.deaths++;this.emit('rescue',(p.id===0?'科迪':'小梅')+'将从最近路标回来，机关进度保留');}
tick(dt,held={},pressed={}){if(this.finished)return;this.t+=dt;for(const p of this.players){const c=controls[p.id];p.cool=Math.max(0,p.cool-dt);p.anim=Math.max(0,p.anim-dt);if(p.recover>0){p.recover-=dt;if(p.recover<=0){Object.assign(p,p.checkpoint);p.recover=0;p.vy=0;p.ground=true;}continue;}if(p.tween){const tw=p.tween;tw.t=Math.min(1,tw.t+dt/tw.duration);const q=tw.t*tw.t*(3-2*tw.t);p.x=tw.start.x+(tw.end.x-tw.start.x)*q;p.z=tw.start.z+(tw.end.z-tw.start.z)*q;p.y=tw.start.y+(tw.end.y-tw.start.y)*q+Math.sin(tw.t*Math.PI)*tw.arc;if(tw.t===1){p.tween=null;p.ground=true;p.vy=0;}continue;}
if(pressed[c.ready]){p.ready=!p.ready;this.emit('prepare',(p.id===0?'科迪':'小梅')+(p.ready?'能力已准备，点按使用键：科迪 Enter，小梅左 Ctrl':'收起能力'));}if(pressed[this.fireKeys[p.id]]||(p.id===0&&(pressed.Enter||pressed.NumpadEnter||pressed.ControlRight)))this.fire(p.id);
let dx=(held[c.right]?1:0)-(held[c.left]?1:0),dz=(held[c.down]?1:0)-(held[c.up]?1:0);const norm=Math.hypot(dx,dz);if(norm>1){dx/=norm;dz/=norm;}if(p.rooted){dx=0;dz=0;}p.vx=dx*4.7;p.vz=dz*4.7;if(norm&&!p.rooted)p.face=Math.atan2(dx,dz);if(pressed[c.jump]&&p.ground&&!p.rooted){p.vy=8;p.ground=false;this.emit('jump');}
const oldX=p.x,oldZ=p.z;if(!this.blocked(p.x+p.vx*dt,p.y,p.z))p.x+=p.vx*dt;if(!this.blocked(p.x,p.y,p.z+p.vz*dt))p.z+=p.vz*dt;for(const floor of this.floors())if(floor.y>p.y+.15&&inside(p.x,p.z,floor,.25)){p.x=oldX;p.z=oldZ;}
const oldY=p.y;p.vy-=21*dt;p.y+=p.vy*dt;let floor=null;for(const r of this.floors())if(inside(p.x,p.z,r,.08)&&p.vy<=0&&oldY>=r.y-.035&&p.y<=r.y+.035&&(!floor||r.y>floor.y))floor=r;if(floor){p.y=floor.y;p.vy=0;p.ground=true;}else p.ground=false;
if(this.level===3&&p.y<.6){for(const o of this.config.objects)if(!this.flags[o.id+'dead']&&Math.hypot(p.x-o.x,p.z-o.z)<.75)this.recover(p);}
if(p.y<-4||Math.abs(p.x)>19||Math.abs(p.z)>12)this.recover(p);
}
for(const shot of this.shots){shot.life-=dt;const o=this.config.objects.find(o=>o.id===shot.to);if(!o){shot.life=0;continue;}const dx=o.x-shot.x,dy=(o.y||0)+.4-shot.y,dz=o.z-shot.z,d=Math.hypot(dx,dy,dz);if(d<dt*17+.15){this.hit(shot.from,shot.to);shot.life=0;}else{shot.x+=dx/d*dt*17;shot.y+=dy/d*dt*17;shot.z+=dz/d*dt*17;}}this.shots=this.shots.filter(s=>s.life>0);
const exit=this.config.exit,both=this.players.every(p=>p.ground&&!p.recover&&!p.tween&&Math.hypot(p.x-exit[0],p.z-exit[1])<2.2);this.finishTime=this.ready()&&both?this.finishTime+dt:0;if(this.finishTime>.7){this.finished=true;this.emit('complete');}}
status(){const f=this.flags;switch(this.level){case 0:return['锤击抬板 '+(f.pin||f.raisedUntil>this.t?'✓':'○'),'钉子固定 '+(f.pin?'✓':'○')];case 1:return['挂钉 '+(f.nail?'✓':'○'),'摆荡 '+(f.swung?'✓':'○'),'接桥 '+(f.release?'✓':'○')];case 2:return['树液配重 '+Math.min(3,f.pan||0)+'/3','障碍涂液 '+(f.resin?'✓':'○'),'火柴引爆 '+(f.burn?'✓':'○')];case 3:return['涂好树液 '+[0,1,2].filter(i=>f['wasp'+i+'sap']&&!f['wasp'+i+'dead']).length,'清除黄蜂 '+[0,1,2].filter(i=>f['wasp'+i+'dead']).length+'/3'];case 4:return['倒转时间 '+(f.clone?'固定':Math.max(0,Math.ceil((f.timeUntil||0)-this.t))+'秒'),'分身踏板 '+(f.clone?'✓':'○')];case 5:return['藤蔓 '+(f.soil?'扎根':'待唤醒'),'浇水 '+Math.min(3,f.water||0)+'/3','杂草 '+(f.weed?'已清除':'待割开')];}}
}
const api={Coop,levels,controls,rect,inside};if(typeof module!=='undefined')module.exports=api;else root.StarCoop=api;
})(typeof window!=='undefined'?window:globalThis);
